# Generated by Django 2.2.13 on 2020-06-10 07:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0027_auto_20170801_1228_squashed_0033_auto_20180606_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='featureinfo_type',
            field=models.CharField(choices=[('type_property', 'Property-Label'), ('type_href', 'HREF-Link'), ('type_image', 'Image')], default='type_property', help_text='specifies if the attribute should be rendered with an HTML widget on GetFeatureInfo template.', max_length=255, verbose_name='featureinfo type'),
        ),
        migrations.AddField(
            model_name='layer',
            name='featureinfo_custom_template',
            field=tinymce.models.HTMLField(blank=True, help_text='the custom GetFeatureInfo template HTML contents.', null=True, verbose_name='featureinfo custom template'),
        ),
        migrations.AddField(
            model_name='layer',
            name='use_featureinfo_custom_template',
            field=models.BooleanField(default=False, help_text='specifies wether or not use a custom GetFeatureInfo template.', verbose_name='use featureinfo custom template?'),
        ),
    ]
