# Generated by Django 2.2.13 on 2020-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0031_auto_20200612_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='featureinfo_type',
            field=models.CharField(choices=[('type_property', 'Label'), ('type_href', 'URL'), ('type_image', 'Image'), ('type_video_mp4', 'Video (mp4)'), ('type_video_ogg', 'Video (ogg)'), ('type_video_webm', 'Video (webm)'), ('type_video_3gp', 'Video (3gp)'), ('type_video_flv', 'Video (flv)'), ('type_video_youtube', 'Video (YouTube/VIMEO - embedded)'), ('type_audio', 'Audio'), ('type_iframe', 'IFRAME')], default='type_property', help_text='specifies if the attribute should be rendered with an HTML widget on GetFeatureInfo template.', max_length=255, verbose_name='featureinfo type'),
        ),
    ]
