# Generated by Django 2.2.13 on 2020-06-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0028_auto_20200323_1945'),
        ('layers', '0032_auto_20200612_1544'),
    ]

    operations = [
    ]
