# Generated by Django 2.2.20 on 2021-05-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0034_auto_20210329_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='upload_session',
        ),
        migrations.DeleteModel(
            name='LayerFile',
        ),
        migrations.DeleteModel(
            name='UploadSession',
        ),
    ]
