# Generated by Django 3.2.4 on 2021-07-20 17:09

from django.db import migrations, models

from geonode.services.enumerations import INDEXED


def update_remotes_attributes(apps, schema_editor):
    """Updating Remote Services related attributes

     - For the time being we need to iterate over the layers since the remote service properties
       are built at runtime and therefore we cannot benefit of an optimized Subquery.
    """
    MyModel = apps.get_model('layers', 'Layer')

    for _m in MyModel.objects.filter(models.Q(remote_service__isnull=False)):
        ows_url = _m.remote_service.service_url if _m.remote_service.method == INDEXED else _m.ows_url
        MyModel.objects.filter(pk=_m).update(
            ows_url=ows_url,
            sourcetype='REMOTE',
            ptype=_m.remote_service.ptype,
            remote_typename=_m.remote_service.name)


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0036_remove_layer_storetype'),
        ('base', '0070_auto_20210720_1709')
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='ptype',
            field=models.CharField(default='gxp_wmscsource', max_length=80, verbose_name='P-Type'),
        ),
        migrations.RunPython(update_remotes_attributes)
    ]
