# Generated by Django 3.2.4 on 2021-07-20 17:09

from django.db import migrations, models


def update_remotes_attributes(apps, schema_editor):
    MyModel = apps.get_model('layers', 'Layer')

    # Updating 'remote_typename' and 'ptype'
    for _m in MyModel.objects.filter(models.Q(remote_service__isnull=False)):
        MyModel.objects.filter(pk=_m).update(
            sourcetype='REMOTE',
            ptype=_m.remote_service.ptype,
            remote_typename=_m.remote_service.name)

    # Updating 'sourcetype' and 'ows_url'
    for _m in MyModel.objects.filter(models.Q(remote_service__isnull=False) & models.Q(remote_service__method="I")):
        MyModel.objects.filter(pk=_m).update(ows_url=_m.remote_service.service_url)


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0036_remove_layer_storetype'),
        ('base', '0070_auto_20210720_1709')
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='ptype',
            field=models.CharField(default='gxp_wmscsource', max_length=80, verbose_name='P-Type'),
        ),
        migrations.RunPython(update_remotes_attributes)
    ]
