# Generated by Django 3.2.12 on 2022-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0042_alter_dataset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='ptype',
            field=models.CharField(default='gxp_wmscsource', max_length=255, verbose_name='P-Type'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='store',
            field=models.CharField(max_length=255, verbose_name='Store'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='typename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Typename'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='workspace',
            field=models.CharField(max_length=255, verbose_name='Workspace'),
        ),
    ]
