# Generated by Django 4.2.9 on 2024-07-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0044_alter_dataset_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="description of attribute to be used in metadata",
                null=True,
                verbose_name="attribute description",
            ),
        ),
    ]
