# Generated by Django 5.2 on 2025-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0044_alter_dataset_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="style",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
