# Generated by Django 5.2 on 2025-10-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0045_alter_attribute_id_alter_style_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataset",
            name="abstract_en",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="constraints_other_en",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="data_quality_statement_en",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="purpose_en",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="supplemental_information_en",
        ),
        migrations.RemoveField(
            model_name="dataset",
            name="title_en",
        ),
    ]
