# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-27 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_client', '0004_auto_20180416_1319'),
    ]

    database_operations = [
        migrations.AlterModelTable('GeoNodeThemeCustomization', 'geonode_themes_geonodethemecustomization'),
        migrations.AlterModelTable('Partner', 'geonode_themes_partner')
    ]

    state_operations = [
        migrations.DeleteModel('GeoNodeThemeCustomization'),
        migrations.DeleteModel('Partner')
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
