# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0003_auto_20190503_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller',
            field=models.TextField(default='#DATA_CONTROLLER'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller_address',
            field=models.TextField(default='#DATA_CONTROLLER_ADDRESS'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller_email',
            field=models.TextField(default='#DATA_CONTROLLER_EMAIL'),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='cookie_law_info_data_controller_phone',
            field=models.TextField(default='#DATA_CONTROLLER_PHONE'),
        ),
    ]
