# Generated by Django 1.11.26 on 2019-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0007_auto_20190510_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='footer_href_color',
            field=models.CharField(default='#ff8f31', max_length=10),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='footer_text_color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='search_bg_color',
            field=models.CharField(default='#333333', max_length=10),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='search_link_color',
            field=models.CharField(default='#ff8f31', max_length=10),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='search_title_color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
