# Generated by Django 2.2.9 on 2020-01-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0009_geonodethemecustomization_footer_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='jumbotron_cta_hide',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hide call to action'),
        ),
    ]
