# Generated by Django 2.2.13 on 2020-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0010_auto_20200115_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumbotronThemeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=255, unique=True)),
                ('jumbotron_slide_image', models.ImageField(upload_to='img/%Y/%m', verbose_name='Jumbotron slide background')),
                ('jumbotron_slide_content', models.TextField(blank=True, help_text='Fill in this section with markdown', null=True, verbose_name='Jumbotron slide content')),
                ('hide_jumbotron_slide_content', models.BooleanField(default=False, help_text='Check this if the jumbotron background image already contains text', verbose_name='Hide text in the jumbotron slide')),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabling this slide will hide it from the slide show')),
            ],
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='welcome_theme',
            field=models.CharField(choices=[('JUMBOTRON_BG', 'jumbotron background'), ('SLIDE_SHOW', 'slide show')], default='JUMBOTRON_BG', help_text='Choose between using jumbotron background and slide show', max_length=255),
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='jumbotron_slide_show',
            field=models.ManyToManyField(blank=True, to='geonode_themes.JumbotronThemeSlide'),
        ),
    ]
