# Generated by Django 3.2.4 on 2021-07-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0012_auto_20210716_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
