# Generated by Django 3.2.12 on 2022-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0013_delete_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geonodethemecustomization',
            name='variant',
        ),
        migrations.AddField(
            model_name='geonodethemecustomization',
            name='extra_css',
            field=models.TextField(blank=True, help_text='This field can be used to insert additional css rules. For example they can be used to customise the Mapstore client custom_theme.html template)', null=True, verbose_name='Custom CSS rules'),
        ),
    ]
