# Generated by Django 3.2.21 on 2023-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_themes', '0014_auto_20220214_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geonodethemecustomization',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Set this theme as the current global theme for GeoNode. This will disable the current theme (if any)'),
        ),
    ]
