# Generated by Django 3.2 on 2021-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapps', '0002_remove_geoapp_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoAppData',
        ),
    ]
