# Generated by Django 3.2.4 on 2021-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapps', '0002_auto_20210615_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoapp',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
    ]
