# Generated by Django 3.2.4 on 2021-06-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapps', '0003_alter_geoapp_name'),
        ('geoapps', '0003_update_detail_url'),
    ]

    operations = [
    ]
