# Generated by Django 3.2.4 on 2021-07-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapps', '0004_merge_0003_alter_geoapp_name_0003_update_detail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoapp',
            name='center_x',
        ),
        migrations.RemoveField(
            model_name='geoapp',
            name='center_y',
        ),
        migrations.RemoveField(
            model_name='geoapp',
            name='projection',
        ),
        migrations.RemoveField(
            model_name='geoapp',
            name='urlsuffix',
        ),
        migrations.RemoveField(
            model_name='geoapp',
            name='zoom',
        ),
    ]
