# Generated by Django 3.2.4 on 2021-07-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapps', '0005_auto_20210705_1121'),
    ]

    operations = [
    ]
