# Generated by Django 5.2.17 on 2026-08-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geoapps", "0006_geoapp_blob_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geoapp",
            options={},
        ),
    ]
