# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_metric_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevent',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='List of resources affected', related_name='requests', to='monitoring.MonitoredResource'),
        ),
    ]
