# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_service_last_check_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricnotificationcheck',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='metricnotificationcheck',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value_num',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmetricdefinition',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmetricdefinition',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_lat',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_lon',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=11, null=True),
        ),
    ]
