# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_auto_20190605_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'OWS:TMS', b'TMS'), (b'OWS:WMS-C', b'WMS-C'), (b'OWS:WMTS', b'WMTS'), (b'OWS:WCS', b'WCS'), (b'OWS:WFS', b'WFS'), (b'OWS:WMS', b'WMS'), (b'OWS:WPS', b'WPS'), (b'other', b'Non-OWS'), (b'OWS:ALL', b'Any OWS'), (b'all', b'All'), (b'create', b'Create'), (b'upload', b'Upload'), (b'change', b'Change'), (b'change_metadata', b'Change Metadata'), (b'view_metadata', b'View Metadata'), (b'view', b'View'), (b'download', b'Download'), (b'publish', b'Publish'), (b'remove', b'Remove'), (b'geoserver', b'Geoserver event')], max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='metricnotificationcheck',
            name='ows_service',
        ),
        migrations.RemoveField(
            model_name='notificationmetricdefinition',
            name='use_ows_service',
        ),
        migrations.RemoveField(
            model_name='requestevent',
            name='ows_service',
        ),
        migrations.AddField(
            model_name='notificationmetricdefinition',
            name='use_event_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='user_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='user_identifier',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredresource',
            name='type',
            field=models.CharField(choices=[(b'', b'No resource'), (b'layer', b'Layer'), (b'map', b'Map'), (b'resource base', b'Resource base'), (b'document', b'Document'), (b'style', b'Style'), (b'admin', b'Admin'), (b'url', b'URL'), (b'other', b'Other')], default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricnotificationcheck',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.EventType'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='monitoring.EventType'),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.EventType'),
        ),
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together=set(
                [('valid_from', 'valid_to', 'service', 'service_metric', 'resource', 'label', 'event_type')]),
        ),
        migrations.RemoveField(
            model_name='metricvalue',
            name='ows_service',
        ),
        migrations.DeleteModel(
            name='OWSService',
        ),
    ]
