# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_monitoredresource_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metriclabel',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
