# Generated by Django 2.2.9 on 2020-01-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_auto_20190830_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricnotificationcheck',
            name='definition',
            field=models.OneToOneField(null=True, on_delete=models.CASCADE, related_name='metric_check', to='monitoring.NotificationMetricDefinition'),
        ),
    ]
