# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_auto_20190830_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionevent',
            name='error_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionevent',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
