# Generated by Django 2.2.10 on 2020-03-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_auto_20200115_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricnotificationcheck',
            name='definition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_check', to='monitoring.NotificationMetricDefinition'),
        ),
    ]
