# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_auto_20200217_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionevent',
            name='error_data',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='exceptionevent',
            name='error_message',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
