# Generated by Django 2.2.15 on 2020-10-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_auto_20200305_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionevent',
            name='error_message',
            field=models.TextField(default=''),
        ),
    ]
