# Generated by Django 3.2.4 on 2021-07-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0032_alter_monitoredresource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredresource',
            name='type',
            field=models.CharField(choices=[('', 'No resource'), ('dataset', 'Dataset'), ('map', 'Map'), ('resource_base', 'Resource base'), ('document', 'Document'), ('style', 'Style'), ('admin', 'Admin'), ('url', 'URL'), ('other', 'Other')], default='', max_length=255),
        ),
    ]
