# Generated by Django 3.2.4 on 2021-07-19 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0068_rename_storetype_resourcebase_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRequest',
            fields=[
                ('exec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('failed', 'failed'), ('running', 'running'), ('finished', 'finished')], default='ready', max_length=50)),
                ('func_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('input_params', models.JSONField(null=True)),
                ('output_params', models.JSONField(null=True)),
                ('geonode_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resourcebase')),
            ],
        ),
    ]
