# Generated by Django 3.2.4 on 2021-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_executionrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrequest',
            name='input_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='output_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
