# Generated by Django 3.2.13 on 2022-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20210719_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='step',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
