# Generated by Django 3.2.13 on 2022-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_executionrequest_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='log',
            field=models.TextField(default=None, null=True),
        ),
    ]
