# Generated by Django 3.2.14 on 2022-07-22 10:05

from django.db import migrations, models

from geonode.resource.enumerator import ExecutionRequestAction

def fixup_action(apps, _):
    execution_requests = apps.get_model('resource', 'ExecutionRequest')
    for _req in execution_requests.objects.all():
        if not _req.action or _req.action == ExecutionRequestAction.unknown.value:
            if getattr(ExecutionRequestAction, _req.func_name, None):
                _req.action = getattr(ExecutionRequestAction, _req.func_name).value
            elif _req.action in ['remove_permissions', "set_permissions"]:
                _req.action = ExecutionRequestAction.permissions.value
            else:
                _req.action = ExecutionRequestAction.unknown.value
            _req.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_executionrequest_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='action',
            field=models.CharField(choices=[('upload', 'upload'), ('create', 'create'), ('copy', 'copy'), ('delete', 'delete'), ('permissions', 'permissions'), ('update', 'update'), ('ingest', 'ingest'), ('unknown', 'unknown')], default='unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='executionrequest',
            name='name',
            field=models.CharField(default=None, help_text='Human readable name for the execution request', max_length=250, null=True),
        ),
        migrations.RunPython(fixup_action, migrations.RunPython.noop)
    ]
