# Generated by Django 3.2.14 on 2022-07-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_executionrequest_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrequest',
            name='action',
            field=models.CharField(choices=[('import', 'import'), ('create', 'create'), ('copy', 'copy'), ('delete', 'delete'), ('permissions', 'permissions'), ('update', 'update'), ('ingest', 'ingest'), ('unknown', 'unknown')], default='unknown', max_length=50, null=True),
        ),
    ]
