# Generated by Django 4.2.9 on 2024-10-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0008_executionrequest_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executionrequest",
            name="source",
        ),
        migrations.AlterField(
            model_name="executionrequest",
            name="action",
            field=models.CharField(
                choices=[
                    ("import", "import"),
                    ("upload", "upload"),
                    ("create", "create"),
                    ("copy", "copy"),
                    ("delete", "delete"),
                    ("permissions", "permissions"),
                    ("update", "update"),
                    ("ingest", "ingest"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=50,
                null=True,
            ),
        ),
    ]
