# Generated by Django 4.2.21 on 2025-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0009_remove_executionrequest_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionrequest",
            name="action",
            field=models.CharField(
                choices=[
                    ("import", "import"),
                    ("upload", "upload"),
                    ("create", "create"),
                    ("copy", "copy"),
                    ("delete", "delete"),
                    ("permissions", "permissions"),
                    ("update", "update"),
                    ("ingest", "ingest"),
                    ("harvest", "harvest"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=50,
                null=True,
            ),
        ),
    ]
