# Generated by Django 4.2.23 on 2025-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0010_alter_executionrequest_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionrequest",
            name="tasks",
            field=models.JSONField(
                blank=True, default=dict, help_text="Tracks the status of each task during the upload"
            ),
        ),
    ]
