# Generated by Django 4.2.23 on 2025-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0011_executionrequest_tasks"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS django_celery_results_taskresult CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS django_celery_results_groupresult CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS django_celery_results_chordcounter CASCADE;"),
    ]
