name: Build Docker Image

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag-version:
        description: 'version tag'     
        required: true
        default: 'v'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{  github.ref_name }} .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{  github.ref_name }}
