# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_auto_20180105_1631_squashed_0028_auto_20180606_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
