# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-06 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_auto_20200313_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
