# Generated by Django 2.2.9 on 2020-01-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_auto_20200114_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=models.CASCADE, to='auth.Group'),
        ),
    ]
