# Generated by Django 2.2.10 on 2020-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_auto_20200221_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
