# Generated by Django 2.2.10 on 2020-03-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0031_auto_20200304_1434'),
        ('groups', '0031_auto_20200305_1522'),
    ]

    operations = [
    ]
