# Generated by Django 2.2.11 on 2020-03-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_merge_20200306_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
