# Generated by Django 2.2.11 on 2020-05-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0033_auto_20200321_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
