# Generated by Django 5.2 on 2025-10-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0034_auto_20200512_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupcategory",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="groupprofile",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="groupprofile",
            name="title_en",
        ),
    ]
