#===========================================================================
# allowed DPIs
#===========================================================================
dpis: [75, 150, 300]

formats:
  - pdf
  - png
  - jpeg

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000

disableScaleLocking: true

#===========================================================================
# the list of allowed ips
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !dnsMatch
    host: otile1.mqcdn.com
    port: 80
  - !dnsMatch
    host: otile2.mqcdn.com
    port: 80
  - !dnsMatch
    host: otile3.mqcdn.com
    port: 80
  - !dnsMatch
    host: otile4.mqcdn.com
    port: 80
  - !dnsMatch
    host: otile5.mqcdn.com
    port: 80
  - !dnsMatch
    host: a.tile.openstreetmap.org
    port: 80
  - !dnsMatch
    host: b.tile.openstreetmap.org
    port: 80
  - !dnsMatch
    host: c.tile.openstreetmap.org
    port: 80
  - !dnsMatch
    host: d.tile.openstreetmap.org
    port: 80
  - !dnsMatch
    host: lipad.tst.dream.upd.edu.ph
    port: 80
  - !dnsMatch
    host: lipad.stg.dream.upd.edu.ph
    port: 80

layouts:
  Image:
    mainPage:
      items:
        - !map
          width: 672
          height: 358
          spacingAfter: 0
  A4 portrait:
    mainPage:
      pageSize: A4
      rotation: true
      items:
        - !text
          text: '${mapTitle}'
          fontSize: 30
          spacingAfter: 0
        - !map
          spacingAfter: 30
          width: 440
          height: 483
        - !scalebar
          type: bar
          maxSize: 100
          barBgColor: white
          fontSize: 8
          align: right
          units: m
        - !text
          font: Helvetica
          fontSize: 9
          align: right
          text: 'scale: 1:${scale} | date printed: ${now MM.dd.yyyy}'
        - !text
          font: Helvetica
          fontSize: 9
          align: left
          text: 'Abstract:'
        - !text
          font: Helvetica
          fontSize: 9
          align: left
          text: '${abstract}'
        - !text
          font: Helvetica
          fontSize: 9
          align: left
          text: 'Purpose'
        - !text
          font: Helvetica
          fontSize: 9
          align: left
          text: '${purpose}'

  Phillidar1:
    mainPage:
      pageSize: A4
      landscape: true
      marginLeft: 40
      marginRight: 40
      marginTop: 20
      marginBottom: 20
      items:
        - !table
          widths: [476,286]
          items:
            - !map
              width: 476
              height: 555
            - !text
              text: '${mapTitle}'

