version: '3.9'

services:

  # Our custom django application. It includes Geonode.
  django:
    env_file:
      - .env_test
    environment:
      - IS_CELERY=False

  # Celery worker that executes celery tasks created by Django.
  celery:
    env_file:
      - .env_test
    environment:
      - IS_CELERY=True

  # Nginx is serving django static and media files and proxies to django and geonode
  geonode:
    env_file:
      - .env_test
  # Gets and installs letsencrypt certificates
  letsencrypt:
    env_file:
      - .env_test
  # Geoserver backend
  geoserver:
    env_file:
      - .env_test
    ports:
      - "8080:8080"