# Generated by Django 2.2.20 on 2021-09-06 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCommandJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=250)),
                ('app_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('args', models.TextField(blank=True, default='[]')),
                ('kwargs', models.TextField(blank=True, default='{}')),
                ('celery_result_id', models.UUIDField(blank=True, null=True)),
                ('output_message', models.TextField(null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('STARTED', 'Started'), ('FINISHED', 'Finished')], default='CREATED', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
