export const GEONODE_RESPONSE_SEQUENCE = 'GEONODE_RESPONSE_SEQUENCE';
export const GEONODE_THROUGHPUT_SEQUENCE = 'GEONODE_THROUGHPUT_SEQUENCE';
export const GEONODE_ERROR_SEQUENCE = 'GEONODE_ERROR_SEQUENCE';
