# Generated by Django 1.11.20 on 2019-04-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20171130_0600_squashed_0041_auto_20190404_0820'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
            ],
        ),
    ]
