# Generated by Django 2.2.16 on 2020-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20200115_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='probe',
            field=models.IntegerField(default=200),
        ),
    ]
