# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 01:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20171212_0518'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
