# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_service_proxy_base'),
        ('services', '0032_auto_20180302_0430'),
    ]

    operations = [
    ]
