# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestjob',
            name='details',
            field=models.TextField(blank=True, default='Resource is queued', null=True),
        ),
    ]
