# Generated by Django 1.11.20 on 2019-03-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_auto_20180414_2120'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
            ],
        ),
    ]
