# Generated by Django 2.2.20 on 2021-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_update_metadata_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
