# Generated by Django 2.2.20 on 2021-06-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_auto_20210519_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': (('add_resourcebase_from_service', 'Can add resources to Service'),)},
        ),
    ]
