# Generated by Django 2.2.20 on 2021-06-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_auto_20210628_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': (('add_resourcebase_from_service', 'Can add resources to Service'), ('change_resourcebase_metadata', 'Can change resources metadata'))},
        ),
    ]
