# Generated by Django 2.2.20 on 2021-09-03 14:27

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_auto_20210629_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_queryparams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='operations',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
