# Generated by Django 3.2.4 on 2021-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_auto_20210629_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_queryparams',
            field=models.TextField(blank=True, null=True),
        ),
    ]
