# Generated by Django 3.2.4 on 2021-09-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_service_harvester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='probe',
        ),
    ]
