# Generated by Django 3.2.7 on 2021-10-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_auto_20210930_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='access_constraints',
        ),
        migrations.RemoveField(
            model_name='service',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='service',
            name='connection_params',
        ),
        migrations.RemoveField(
            model_name='service',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='service',
            name='first_noanswer',
        ),
        migrations.RemoveField(
            model_name='service',
            name='noanswer_retries',
        ),
        migrations.RemoveField(
            model_name='service',
            name='online_resource',
        ),
        migrations.RemoveField(
            model_name='service',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='service',
            name='password',
        ),
        migrations.RemoveField(
            model_name='service',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='service',
            name='proxy_base',
        ),
        migrations.RemoveField(
            model_name='service',
            name='resources_ref',
        ),
        migrations.RemoveField(
            model_name='service',
            name='store_ref',
        ),
        migrations.RemoveField(
            model_name='service',
            name='username',
        ),
        migrations.RemoveField(
            model_name='service',
            name='workspace_ref',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('OWS', 'Paired WMS/WFS/WCS'), ('WMS', 'Web Map Service'), ('GN_WMS', 'GeoNode (Web Map Service)')], max_length=100),
        ),
    ]
