# Generated by Django 3.2.7 on 2021-10-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_auto_20211004_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('OWS', 'Paired WMS/WFS/WCS'), ('WMS', 'Web Map Service'), ('REST_MAP', 'ArcGIS REST MapServer'), ('REST_IMG', 'ArcGIS REST ImageServer'), ('GN_WMS', 'GeoNode (Web Map Service)')], max_length=100),
        ),
    ]
