# Generated by Django 3.2.12 on 2022-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('WMS', 'Web Map Service'), ('GN_WMS', 'GeoNode (Web Map Service)'), ('REST_MAP', 'ArcGIS REST MapServer'), ('REST_IMG', 'ArcGIS REST ImageServer')], max_length=10),
        ),
    ]
