# Generated by Django 4.2.20 on 2025-03-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0054_alter_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="password",
            field=models.CharField(default=None, max_length=250, null=True, verbose_name="password"),
        ),
        migrations.AddField(
            model_name="service",
            name="username",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
