# Generated by Django 4.2.20 on 2025-05-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0055_service_password_service_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="password",
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="service",
            name="username",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
