# Generated by Django 5.2 on 2025-10-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0056_alter_service_password_alter_service_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name_en",
        ),
    ]
