# Generated by Django 5.2.13 on 2026-05-08 05:19

import base64
import hashlib
import json

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations


def migrate_service_auth_to_auth_config(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    AuthConfig = apps.get_model("security", "AuthConfig")

    encryption_key = base64.urlsafe_b64encode(hashlib.sha256(settings.SECRET_KEY.encode()).digest())
    cipher = Fernet(encryption_key)

    legacy_services = Service.objects.filter(
        username__isnull=False,
        password__isnull=False,
    )

    for service in legacy_services.iterator():
        raw_password = cipher.decrypt(service.password.encode()).decode()
        encrypted_payload = cipher.encrypt(
            json.dumps({"username": service.username, "password": raw_password}).encode()
        ).decode()

        auth_config = AuthConfig.objects.create(type="basic", _payload=encrypted_payload)
        Service.objects.filter(pk=service.pk).update(auth_config=auth_config)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0099_resourcebase_auth_config"),
        ("security", "0001_initial"),
        ("services", "0057_remove_modeltranslation"),
    ]

    operations = [migrations.RunPython(migrate_service_auth_to_auth_config, migrations.RunPython.noop)]
