# Generated by Django 5.2.13 on 2026-05-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0058_migrate_service_auth_to_auth_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="password",
        ),
        migrations.RemoveField(
            model_name="service",
            name="username",
        ),
    ]
