# Generated by Django 5.2.15 on 2026-06-09 12:56

import geonode.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0059_remove_service_password_remove_service_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(choices=geonode.services.models.get_service_type_choices, max_length=10),
        ),
    ]
