# Generated by Django 5.2.13 on 2026-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0060_alter_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="base_url",
            field=models.URLField(db_index=True),
        ),
    ]

