# Generated by Django 5.2.17 on 2026-08-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"base_manager_name": "objects", "verbose_name_plural": "Assets"},
        ),
    ]
