# Generated by Django 4.2.9 on 2024-07-11 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("campaign_id", models.AutoField(primary_key=True, serialize=False)),
                ("campaign_name", models.CharField(max_length=255)),
                (
                    "campaign_url_name",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only lowercase letters, numbers, hyphens, and underscores allowed.",
                                regex="^[a-z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                ("allow_drawings", models.BooleanField(default=True)),
                ("rate_enabled", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("campaing_detailed_description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="campaign_images/")),
                ("image_description", models.CharField(blank=True, max_length=255, null=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cpt.campaign")),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="categories",
            field=models.ManyToManyField(related_name="campaigns", to="cpt.category"),
        ),
    ]
