# Generated by Django 4.2.9 on 2024-08-21 09:17

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("campaign_id", models.AutoField(primary_key=True, serialize=False)),
                ("campaign_name", models.CharField(max_length=255)),
                (
                    "campaign_url_name",
                    models.SlugField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Only lowercase letters, numbers, hyphens, and underscores allowed.",
                                regex="^[a-z0-9\\-_]+$",
                            )
                        ],
                    ),
                ),
                ("campaing_title", models.CharField(max_length=255)),
                ("campaing_short_description", models.CharField(max_length=255)),
                ("campaing_detailed_description", models.TextField()),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                ("rate_enabled", models.BooleanField(blank=True, default=True, null=True)),
                ("form_enabled", models.BooleanField(blank=True, default=False, null=True)),
                ("allow_drawings", models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feedback_location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("feedback_text", models.TextField()),
                ("feedback_category", models.CharField(max_length=100)),
                ("feedback_geometry", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forms", to="cpt.campaign"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoserverLayers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("layer_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="cpt.campaign"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings",
                        to="cpt.form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="cpt.categorytype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="cpt.categorytype",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="geoserver_layers",
            field=models.ManyToManyField(related_name="campaigns", to="cpt.geoserverlayers"),
        ),
    ]
