# Generated by Django 4.2.9 on 2024-07-12 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_name",
        ),
        migrations.AddField(
            model_name="category",
            name="input_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="allow_drawings",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_url_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only lowercase letters, numbers, hyphens, and underscores allowed.",
                        regex="^[a-z0-9\\-_]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaing_detailed_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="rate_enabled",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="CampaignImage",
        ),
        migrations.AddField(
            model_name="campaign",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="cpt.categorytype",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="cpt.categorytype",
            ),
        ),
    ]
