# Generated by Django 4.2.9 on 2024-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0002_categorytype_remove_campaign_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="title",
            new_name="campaing_title",
        ),
        migrations.RemoveField(
            model_name="category",
            name="input_type",
        ),
        migrations.AddField(
            model_name="campaign",
            name="campaing_short_description",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
