# Generated by Django 4.2.9 on 2024-07-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0003_rename_title_campaign_campaing_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="geoserver_workspace",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
