# Generated by Django 4.2.9 on 2024-07-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0004_campaign_geoserver_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="allow_drawings",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaing_short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
