# Generated by Django 4.2.9 on 2024-08-08 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0005_alter_campaign_allow_drawings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="form_enabled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="allow_drawings",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_name",
            field=models.CharField(default="default_name", max_length=255),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_url_name",
            field=models.SlugField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only lowercase letters, numbers, hyphens, and underscores allowed.",
                        regex="^[a-z0-9\\-_]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaing_detailed_description",
            field=models.TextField(default="default_description"),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaing_short_description",
            field=models.CharField(default="default_short_description", max_length=255),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaing_title",
            field=models.CharField(default="default_title", max_length=255),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateTimeField(default="2021-01-01 00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(default="2021-01-01 00:00:00"),
            preserve_default=False,
        ),
    ]
