# Generated by Django 4.2.9 on 2024-08-09 11:10

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0007_alter_campaign_campaign_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CTPForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feedback_location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("feedback_text", models.TextField()),
                ("feedback_category", models.CharField(max_length=100)),
                ("feedback_geometry", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 9, 11, 10, 11, 618205, tzinfo=datetime.timezone.utc)
            ),
        ),
        migrations.CreateModel(
            name="CTPRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="cpt.campaign"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings",
                        to="cpt.ctpform",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ctpform",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="forms", to="cpt.campaign"
            ),
        ),
    ]
