# Generated by Django 4.2.9 on 2024-08-09 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0008_ctpform_alter_campaign_start_date_ctprating_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CTPForm",
            new_name="Form",
        ),
        migrations.RenameModel(
            old_name="CTPRating",
            new_name="Rating",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 9, 14, 43, 34, 927900, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
