# Generated by Django 2.2.16 on 2021-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0002_auto_20210415_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestingsession',
            name='total_records_found',
            field=models.IntegerField(default=0),
        ),
    ]
