# Generated by Django 2.2.16 on 2021-04-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0005_auto_20210428_1100'),
    ]

    operations = [
    ]
