# Generated by Django 2.2.16 on 2021-05-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0008_auto_20210519_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestableresource',
            name='harvester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvestable_resources', to='harvesting.Harvester'),
        ),
    ]
