# Generated by Django 2.2.16 on 2021-05-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0009_auto_20210519_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestableresource',
            name='should_be_harvested',
            field=models.BooleanField(default=False),
        ),
    ]
