# Generated by Django 2.2.16 on 2021-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0012_auto_20210520_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='last_check_harvestable_resources_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='harvester',
            name='last_checked_harvestable_resources',
            field=models.DateTimeField(blank=True, help_text='Last time the remote server was checked for harvestable resources', null=True),
        ),
    ]
