# Generated by Django 2.2.16 on 2021-05-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0014_auto_20210526_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestableresource',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('updating-harvestable-resource', 'updating-harvestable-resource'), ('harvesting-resource', 'harvesting-resource')], default='ready', max_length=50),
        ),
    ]
