# Generated by Django 3.2.4 on 2021-06-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0019_auto_20210614_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='default_access_permissions',
            field=models.JSONField(default=dict, help_text='Default access permissions of harvested resources'),
        ),
    ]
