# Generated by Django 3.2.4 on 2021-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0024_remove_harvestableresource_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestableresource',
            name='last_harvested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestableresource',
            name='last_harvesting_message',
            field=models.TextField(blank=True),
        ),
    ]
