# Generated by Django 3.2.4 on 2021-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0025_auto_20210624_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestableresource',
            name='last_harvesting_succeeded',
            field=models.BooleanField(default=False),
        ),
    ]
