# Generated by Django 3.2.4 on 2021-07-08 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('harvesting', '0026_harvestableresource_last_harvesting_succeeded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvester',
            name='default_access_permissions',
        ),
    ]
