# Generated by Django 3.2.4 on 2021-08-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0027_remove_harvester_default_access_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='num_harvestable_resources',
            field=models.IntegerField(default=0),
        ),
    ]
