# Generated by Django 3.2.4 on 2021-08-16 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0028_harvester_num_harvestable_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='task_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), blank=True, null=True, size=None),
        ),
    ]
