# Generated by Django 3.2.4 on 2021-09-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0029_dynamic_harvester_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='num_harvestable_resources',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
