# Generated by Django 3.2.4 on 2021-09-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0030_auto_20210917_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestingsession',
            name='total_records_found',
        ),
    ]
