# Generated by Django 3.2.4 on 2021-09-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0031_remove_harvestingsession_total_records_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestingsession',
            name='session_details',
            field=models.TextField(blank=True, help_text='Details about the harvesting session'),
        ),
    ]
