# Generated by Django 3.2.4 on 2021-09-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0032_harvestingsession_session_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('on-going', 'on-going'), ('finished-all-ok', 'finished-all-ok'), ('finished-all-failed', 'finished-all-failed'), ('finished-some-failed', 'finished-some-failed')], default='pending', editable=False, max_length=50),
        ),
    ]
