# Generated by Django 3.2.4 on 2021-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0033_alter_harvestingsession_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='harvester',
            constraint=models.UniqueConstraint(fields=('name',), name='unique name'),
        ),
    ]
