# Generated by Django 3.2.7 on 2021-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0036_alter_harvester_harvester_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='name',
            field=models.CharField(help_text='Harvester name', max_length=255),
        ),
    ]
