# Generated by Django 3.2.7 on 2021-10-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0037_alter_harvester_name'),
        ('harvesting', '0039_delete_harvestingsession'),
    ]

    operations = [
    ]
