# Generated by Django 3.2.4 on 2021-09-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0040_auto_20210927_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HarvestingSession',
        ),
    ]
