# Generated by Django 3.2.4 on 2021-09-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0043_remove_harvester_update_frequency'),
    ]

    operations = [
    ]
