# Generated by Django 3.2.4 on 2021-09-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0044_migrate_harvester_harvesting_session_update_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvester',
            name='update_frequency',
        ),
    ]
