# Generated by Django 3.2.13 on 2022-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0049_alter_harvester_harvester_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='publish_new_resources_by_default',
            field=models.BooleanField(default=True, help_text='Should new resources be automatically published on GeoNode?'),
        ),
    ]
