# Generated by Django 4.2.23 on 2025-09-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvesting", "0049_alter_harvester_harvester_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvester",
            name="harvester_type",
            field=models.CharField(
                choices=[
                    (
                        "geonode.harvesting.harvesters.wms.OgcWmsHarvester",
                        "geonode.harvesting.harvesters.wms.OgcWmsHarvester",
                    ),
                    (
                        "geonode.harvesting.harvesters.geonodeharvester.GeonodeUnifiedHarvesterWorker",
                        "geonode.harvesting.harvesters.geonodeharvester.GeonodeUnifiedHarvesterWorker",
                    ),
                    (
                        "geonode.harvesting.harvesters.arcgis.ArcgisHarvesterWorker",
                        "geonode.harvesting.harvesters.arcgis.ArcgisHarvesterWorker",
                    ),
                ],
                default="geonode.harvesting.harvesters.wms.OgcWmsHarvester",
                help_text="Harvester class used to perform harvesting sessions. New harvester types can be added by an admin by changing the main GeoNode `settings.py` file",
                max_length=255,
            ),
        ),
    ]
