# Generated by Django 3.2.13 on 2022-05-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesting', '0049_alter_harvester_harvester_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='delete_orphan_resources_automatically',
            field=models.BooleanField(default=True, help_text='Orphan resources are those that have previously been created by means of a harvesting operation but that GeoNode can no longer find on the remote service being harvested. Should these resources be deleted from GeoNode automatically? This also applies to when a harvester configuration is deleted, in which case all of the resources that originated from that harvester are now considered to be orphan.'),
        ),
    ]
