#########################################################################
#
# Copyright (C) 2026 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
"""GeoNode REST API v3.

Plain Django REST Framework -- ``ModelViewSet`` and ``ModelSerializer``, no
django-dynamic-rest.

Conventions:

* Field selection is the single ``?fields=`` query parameter, which prunes
  the queryset as well as the serializer.
* A trailing slash is required. ``/api/v3/groups/`` matches; ``/api/v3/groups``
  does not.
* Pagination is bounded -- ``page_size`` has a hard maximum.
* The response envelope is DRF's standard
  ``{"count", "next", "previous", "results"}``.
* OpenAPI is served at ``/api/v3/schema/`` (plus ``swagger-ui/`` and
  ``redoc/``), generated by drf-spectacular -- see :mod:`geonode.api.v3.schema`.

Routes are registered in exactly one place, :mod:`geonode.api.v3.urls`. Nothing
outside this package may register a v3 route, and no ``AppConfig`` mutates the
root URLconf.
"""
