# Generated by Django 5.2.13 on 2026-05-08 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=128)),
                ("_payload", models.CharField(db_column="payload", max_length=4096)),
            ],
            options={
                "verbose_name": "Authentication Configuration",
                "verbose_name_plural": "Authentication Configurations",
            },
        ),
        migrations.CreateModel(
            name="URLPatternAuthConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pattern", models.CharField(max_length=2048)),
                (
                    "auth_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_patterns",
                        to="security.authconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL Pattern Authentication Configuration",
                "verbose_name_plural": "URL Pattern Authentication Configurations",
            },
        ),
    ]
