name: Build image (manual)

on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        required: true
        description: Image
        options: 
        - geoserver
        - geoserver_data
        - nginx
        - postgis
        - letsencrypt
      tag:
        required: true
        description: Image tag
      push:
        type: boolean
        default: false
        description: Push the image to Docker Hub?

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ./docker/${{ github.event.inputs.image }}/Dockerfile
        context: "./docker/${{ github.event.inputs.image }}/"
        push: ${{fromJSON(github.event.inputs.push)}}
        tags: geonode/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
    - name: Final message
      run: echo "Built ${{ github.event.inputs.image }} from branch ${{ github.event.inputs.branch }} (push ${{ fromJSON(github.event.inputs.push) }})"
