name: Release Docker Image (Build and Push)

on:
  release:
    types: [published]

jobs:
  geoserver:
    if: ${{ contains(github.ref, 'geoserver#') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "#"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "geoserver"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  postgis:
    if: ${{ contains(github.ref, 'postgis#') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "#"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "postgis"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  nginx:
    if: ${{ contains(github.ref, 'nginx#') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "#"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "nginx"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  geoserver_data:
    if: ${{ contains(github.ref, 'geoserver_data#') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "#"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "geoserver_data"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  letsencrypt:
    if: ${{ contains(github.ref, 'letsencrypt#') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "#"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "letsencrypt"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
