# Generated by Django 2.2.15 on 2020-10-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20200115_1121'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='profile',
        #     name='agree_conditions',
        #     field=models.BooleanField(default=False, verbose_name='Agree Conditions'),
        # ),
    ]
