# Generated by Django 2.2.15 on 2020-10-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20201001_2047'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='profile',
        #     name='professional_role',
        #     field=models.CharField(blank=True, choices=[('COPART', 'Corporate partner'), ('ACDMC', 'Academic'), ('SCADM', 'Service company administrator'), ('MCOMC', 'Manager that carries out monitoring and control'), ('CITIZN', 'Citizen'), ('REPECS', 'Representative of an economic sector'), ('OTHER', 'Other')], help_text='Professional or Academic user role', max_length=6, null=True, verbose_name='ProfessionalRole'),
        # ),
    ]
