# Generated by Django 2.2.16 on 2020-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_auto_20201004_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_role',
            field=models.CharField(blank=True, help_text='Other Role', max_length=50, null=True, verbose_name='OtherRole'),
        ),
    ]
