# Generated by Django 2.2.16 on 2021-02-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_auto_20210118_1112'),
        ('people', '0030_auto_20210201_0953'),
    ]

    operations = [
    ]
