# Generated by Django 2.2.16 on 2021-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0030_auto_20210118_1112"),
        ("people", "0030_auto_20210201_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="orcid_identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ORCID identifier of profile.",
                max_length=255,
                verbose_name="orcid identifier",
            ),
        ),
    ]
