# Generated by Django 2.2.16 on 2020-11-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_profile_other_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='use_analysis',
            field=models.CharField(blank=True, choices=[('UACDMC', 'Academic'), ('UGNRL', 'General'), ('UBSNSS', 'Business'), ('UOTHER', 'Other')], help_text='Use Analysis', max_length=8, null=True, verbose_name='UseAnalysis'),
        ),
    ]
