# Generated by Django 2.2.16 on 2020-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_profile_use_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_analysis',
            field=models.CharField(blank=True, help_text='Other Analysis', max_length=50, null=True, verbose_name='Other Analisys'),
        ),
    ]
