# Generated by Django 2.2.20 on 2021-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_alter_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
