# Generated by Django 3.2.4 on 2021-07-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0033_set_contributors_permissions'),
        ('people', '0035_alter_profile_first_name'),
    ]

    operations = [
    ]
