# Generated by Django 3.2.18 on 2023-04-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_merge_20210706_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orcid_identifier',
            field=models.CharField(blank=True, default='', help_text='ORCID identifier of profile.', max_length=255, verbose_name='orcid identifier'),
        ),
    ]
