# Generated by Django 2.2.16 on 2020-12-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_profile_agree_conditions'),
        ('people', '0029_auto_20201216_1335'),
    ]

    operations = [
    ]
