# Generated by Django 4.2.23 on 2025-09-15 15:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("people", "0036_merge_20210706_0951"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="keywords",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="commonly used word(s) or formalised word(s) or phrase(s) used to describe the subject             (space or comma-separated)",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="keywords",
            ),
        ),
    ]
