# Generated by Django 2.2.16 on 2020-12-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20201216_1335'),
        ('people', '0037_auto_20201222_1250'),
    ]

    operations = [
    ]
