# Generated by Django 2.2.16 on 2020-12-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_auto_20201220_1623'),
        ('people', '0037_auto_20201222_1250'),
    ]

    operations = [
    ]
