# Generated by Django 5.2.10 on 2026-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0038_migrate_sha1_passwords"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="extra_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="additional profile-related attributes", verbose_name="Extra Data"
            ),
        ),
    ]
