# Generated by Django 2.2.16 on 2021-01-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0039_auto_20201224_1040'),
        ('people', '0038_auto_20210104_2140'),
        ('people', '0038_auto_20201220_1623'),
    ]

    operations = [
    ]
