# Generated by Django 2.2.16 on 2021-01-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0041_auto_20210105_1540'),
        ('people', '0039_merge_20201223_1920'),
    ]

    operations = [
    ]
