# Generated by Django 2.2.16 on 2021-01-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0042_merge_20210106_2133'),
        ('people', '0042_merge_20210106_2040'),
    ]

    operations = [
    ]
