# Generated by Django 2.2.16 on 2021-01-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_auto_20210105_1500'),
        ('people', '0043_merge_20210106_2326'),
    ]

    operations = [
    ]
