# Generated by Django 2.2.16 on 2021-01-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_merge_20210107_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='professional_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('ANALYS', 'Analyst'), ('COPART', 'Corporate partner'), ('ACDMC', 'Academic'), ('SCADM', 'Service company administrator'), ('MCOMC', 'Manager that carries out monitoring and control'), ('CITIZN', 'Citizen'), ('REPECS', 'Representative of an economic sector'), ('OTHER', 'Other')], help_text='Professional or Academic user role', max_length=6, null=True, verbose_name='ProfessionalRole'),
        ),
    ]
