# Generated by Django 2.2.16 on 2021-01-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_merge_20210108_1532'),
        ('people', '0046_auto_20210108_0034'),
    ]

    operations = [
    ]
