# Generated by Django 2.2.16 on 2021-01-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_merge_20210108_0044'),
        ('people', '0047_merge_20210108_1558'),
    ]

    operations = [
    ]
