# Generated by Django 3.2.15 on 2022-10-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resource", "0007_alter_executionrequest_action"),
        ("importer", "0002_resourcehandlerinfo_kwargs"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcehandlerinfo",
            name="execution_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resource.executionrequest",
            ),
        ),
    ]
