# Generated by Django 3.2.15 on 2022-10-04 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0003_resourcehandlerinfo_execution_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcehandlerinfo",
            old_name="execution_id",
            new_name="execution_request",
        ),
    ]
