# Generated by Django 2.2.9 on 2020-01-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '24_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='session',
            field=models.TextField(blank=True, null=True),
        ),
    ]
