# Generated by Django 2.2.11 on 2020-03-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_auto_20200115_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_dir',
            field=models.TextField(null=True),
        ),
    ]
