# Generated by Django 2.2.16 on 2021-03-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_auto_20200321_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='append_to_mosaic_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mosaic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer'),
        ),
    ]
