# Generated by Django 2.2.16 on 2021-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0027_auto_20210329_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='append_to_mosaic_opts',
            field=models.BooleanField(default=False),
        ),
    ]
