# Generated by Django 2.2.16 on 2021-03-29 14:58

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_upload_append_to_mosaic_opts'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(max_length=4096, storage=django.core.files.storage.FileSystemStorage(base_url='/uploaded/'), upload_to='layers/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='slug',
            field=models.SlugField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.Upload'),
        ),
    ]
