# Generated by Django 2.2.16 on 2021-04-07 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0029_auto_20210329_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create_date'),
        ),
    ]
