# Generated by Django 3.2 on 2021-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_upload_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='base',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
