# Generated by Django 3.2 on 2021-05-31 12:52
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_resourcebase_files'),
        ('upload', '0033_auto_20210528_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resourcebase'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
