# Generated by Django 3.2.7 on 2021-12-16 16:36

import django.core.validators
from django.db import migrations, models

DEFAULT_MAX_UPLOAD_SIZE = 104857600  # 100MB

UPLOAD_SIZE_LIMIT_OBJECTS = [
    {"slug": "base_file", "max_size": DEFAULT_MAX_UPLOAD_SIZE},
    {"slug": "dbf_file", "max_size": DEFAULT_MAX_UPLOAD_SIZE},
    {"slug": "shx_file", "max_size": DEFAULT_MAX_UPLOAD_SIZE},
    {"slug": "prj_file", "max_size": DEFAULT_MAX_UPLOAD_SIZE},
    {"slug": "xml_file", "max_size": DEFAULT_MAX_UPLOAD_SIZE},
    {"slug": "sld_file", "max_size": DEFAULT_MAX_UPLOAD_SIZE},
]

def create_upload_size_limit_objects(apps, schema_editor):
    UploadSizeLimit = apps.get_model("upload", "UploadSizeLimit")
    for obj in UPLOAD_SIZE_LIMIT_OBJECTS:
        UploadSizeLimit.objects.create(**obj)

def remove_upload_size_limit_objects(apps, schema_editor):
    UploadSizeLimit = apps.get_model("upload", "UploadSizeLimit")
    UploadSizeLimit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0033_auto_20210531_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSizeLimit',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('max_size', models.PositiveBigIntegerField(default=2621440, help_text='The maximum file size allowed for upload (bytes).')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.RunPython(create_upload_size_limit_objects, remove_upload_size_limit_objects),
    ]
