# Generated by Django 3.2.4 on 2021-08-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0033_auto_20210531_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='resume_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
