# Generated by Django 3.2.12 on 2022-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0035_update_uploadsizelimit_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='spatial_files_uploaded',
            field=models.BooleanField(default=True),
        ),
    ]
