# Generated by Django 3.2.12 on 2022-03-09 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0036_upload_store_spatial_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadParallelismLimit',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('description', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('max_number', models.PositiveSmallIntegerField(default=5, help_text='The maximum number of parallel uploads (0 to 32767).')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
