# Generated by Django 3.2.12 on 2022-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0037_uploadparallelismlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
