# Generated by Django 3.2.13 on 2022-05-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0038_alter_upload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadparallelismlimit',
            name='max_number',
            field=models.PositiveSmallIntegerField(default=100, help_text='The maximum number of parallel uploads (0 to 32767).'),
        ),
        migrations.AlterField(
            model_name='uploadsizelimit',
            name='max_size',
            field=models.PositiveBigIntegerField(default=5368709120, help_text='The maximum file size allowed for upload (bytes).'),
        ),
    ]
