# Generated by Django 3.2.19 on 2023-08-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0039_auto_20220506_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
