# Generated by Django 4.2.9 on 2024-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0047_alter_resourcehandlerinfo_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcehandlerinfo",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
