# Generated by Django 4.2.9 on 2024-09-06 14:46

from django.db import migrations, models
from django.db import connection
from geonode.upload.models import ResourceHandlerInfo

def forwards_func(apps, schema_editor):
    SQL = """
    INSERT INTO
        upload_resourcehandlerinfo (handler_module_path,
        resource_id,
        kwargs,
        execution_request_id)
    SELECT
        handler_module_path,
        resource_id,
        kwargs,
        execution_request_id
    FROM
        importer_resourcehandlerinfo ir;
    """
    
    # checking if the importer table is present. Is false if is a new installation
    
    names = connection.introspection.table_names()
    if 'importer_resourcehandlerinfo' in names:
        with connection.cursor() as cursor:
            cursor.execute(SQL)

    for row in ResourceHandlerInfo.objects.iterator():
        if 'importer.handlers' in row.handler_module_path:
            row.handler_module_path = row.handler_module_path.replace("importer.handlers", "geonode.upload.handlers")
            row.save()
            
    # truncate old TABLE
    SQL = """
    DROP TABLE importer_resourcehandlerinfo
    """
    names = connection.introspection.table_names()
    if 'importer_resourcehandlerinfo' in names:
        with connection.cursor() as cursor:
            cursor.execute(SQL)

class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0048_alter_resourcehandlerinfo_id"),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
