# Generated by Django 4.2.16 on 2024-12-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0049_move_data_from_importer_to_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsizelimit",
            name="max_size",
            field=models.PositiveBigIntegerField(
                default=104857600, help_text="The maximum file size allowed for upload (bytes)."
            ),
        ),
    ]
