# Generated by Django 2.2.16 on 2021-01-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studycases',
            options={},
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='name',
            new_name='dws_name',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='annual_water_yield',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='baseflow',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='carbon_storage',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='contracts',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='erosion_control_drinking_water_qa',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='finance_and_admin',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='flood_mitigation',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='groundwater_recharge_enhancement',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='implementation_manager',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='monitoring_and_evaluation_mngr',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nbs_ca_active_restoration',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nbs_ca_agroforestry',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nbs_ca_conservation',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nbs_ca_passive_restoration',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nbs_ca_silvopastoral',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nutrient_delivery',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nutrient_retention_ni',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nutrient_retention_ph',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='office_costs',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='others',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='overhead',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='personnel_salary_benefits',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='platform_cost_per_year',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='program_director',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='seasonal_water_yield',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='sediment_delivery_ratio',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='sensitive_analysis_max_disc_rate',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='sensitive_analysis_min_disc_rate',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='transaction_costs',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='treatment_plants',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='water_intakes',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='with_carbon_markets',
        ),
        migrations.AddField(
            model_name='studycases',
            name='ciudad_id',
            field=models.IntegerField(default=0, verbose_name='ciudad_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_analysis_period_value',
            field=models.IntegerField(default=0, verbose_name='Years number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_annual_investment_scenario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='dws_annual_investment_scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_authorization_case',
            field=models.CharField(default=0, max_length=20, verbose_name='dws_climate_scenario_scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_benefit_carbon_market',
            field=models.BooleanField(default=False, verbose_name='Benefit carbon'),
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_benefit_function',
            field=models.CharField(default=0, max_length=100, verbose_name='dws_benefit_function'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_climate_scenario_scenario',
            field=models.CharField(default=0, max_length=100, verbose_name='dws_climate_scenario_scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_description',
            field=models.CharField(default=0, max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_id_parent',
            field=models.IntegerField(default=0, verbose_name='dws_id_parent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_modif_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_rio_analysis_time',
            field=models.IntegerField(default=0, verbose_name='dws_rio_analysis_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_time_implement_briefcase',
            field=models.IntegerField(default=0, verbose_name='dws_time_implement_briefcase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_time_implement_scenario',
            field=models.IntegerField(default=0, verbose_name='dws_time_implement_scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_type_money',
            field=models.CharField(default=0, max_length=10, verbose_name='dws_type_money'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_usr_create',
            field=models.IntegerField(default=0, verbose_name='dws_usr_create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='estado_id',
            field=models.IntegerField(default=0, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='region_id',
            field=models.IntegerField(default=0, verbose_name='region_id'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='studycases',
            table='waterproof_study_cases',
        ),
    ]
