# Generated by Django 2.2.16 on 2021-01-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0002_auto_20210114_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studycases',
            options={'managed': False},
        ),
    ]
