# Generated by Django 3.2 on 2021-06-04 07:42

from django.db import migrations
from geonode.layers.models import Layer

LAYER_SUBTYPES = {
    "dataStore": "vector",
    "coverageStore": "raster",
    "remoteStore": "remote",
    "vectorTimeSeries": "vector_time"
}

def change_value(apps, schema_editor):
    MyModel = apps.get_model('layers', 'Layer')
    for l in MyModel.objects.all():
        u = Layer.objects.filter(resourcebase_ptr_id=l.resourcebase_ptr_id)
        store_type = get_layer_storetype(l.storeType)
        u.update(**{"storeType": store_type})


def get_layer_storetype(element):
    return LAYER_SUBTYPES.get(element, element)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_resourcebase_files'),
    ]

    operations = [
        migrations.RunPython(change_value),

    ]
