# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 14:10


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20170801_1228_squashed_0037_auto_20190222_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='curated_thumbs')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
            ],
        ),
    ]
