# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from geonode.base.models import ContactRole


def forwards_func(apps, schema_editor):
    ContactRole.objects.filter(resource_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_resourcebase_created'),
    ]

    operations = [
        migrations.RunPython(forwards_func, lambda a, b: True)
    ]
