# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20200213_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrole',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
    ]
