# Generated by Django 2.2.9 on 2020-01-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20200114_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedthumbnail',
            name='resource',
            field=models.OneToOneField(on_delete=models.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='category',
            field=models.ForeignKey(blank=True, help_text='high-level geographic data thematic classification to assist in the grouping and search of available geographic data sets.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TopicCategory'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='restriction_code_type',
            field=models.ForeignKey(blank=True, help_text='limitation(s) placed upon the access or use of the data.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='base.RestrictionCodeType', verbose_name='restrictions'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='spatial_representation_type',
            field=models.ForeignKey(blank=True, help_text='method used to represent geographic information in the dataset.', limit_choices_to=models.Q(is_choice=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='base.SpatialRepresentationType', verbose_name='spatial representation type'),
        ),
    ]
