# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20180309_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Is this resource validated from a publisher or editor?', verbose_name='Approved'),
        ),
    ]
