# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20180319_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='srid',
            field=models.CharField(default=b'EPSG:4326', max_length=30),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='srid',
            field=models.CharField(default=b'EPSG:4326', max_length=30),
        ),
    ]
