# Generated by Django 2.2.9 on 2020-01-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20200115_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcebase',
            options={'permissions': (('change_resourcebase_permissions', 'Can change resource permissions'), ('download_resourcebase', 'Can download resource'), ('publish_resourcebase', 'Can publish resource'), ('change_resourcebase_metadata', 'Can change resource metadata'))},
        ),
    ]
