# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20200213_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='doi',
            field=models.TextField(blank=True, help_text='a DOI will be added by Admin before publication.', null=True, verbose_name='DOI'),
        ),
    ]
