# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_resourcebase_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='keyword identifies a location', null=True, to='base.Region', verbose_name='keywords region'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='tkeywords',
            field=models.ManyToManyField(blank=True, help_text='formalised word(s) or phrase(s) from a fixed thesaurus used to describe the subject (space or comma-separated', null=True, to='base.ThesaurusKeyword', verbose_name='keywords'),
        ),
    ]
