# Generated by Django 2.2.10 on 2020-02-12 04:10

from django.db import migrations
from geonode.base.models import ContactRole

def forwards_func(apps, schema_editor):
    ContactRole.objects.filter(resource_id__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20200115_1145'),
    ]

    operations = [
        migrations.RunPython(forwards_func, lambda a, b: True)
    ]
