# Generated by Django 2.2.10 on 2020-02-12 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20200212_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrole',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
