# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-02 15:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20180606_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='dirty_state',
            field=models.BooleanField(default=False, help_text='Security Rules Are Not Synched with GeoServer!', verbose_name='Dirty State'),
        ),
    ]
