# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20200315_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
