# Generated by Django 2.2.10 on 2020-03-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20200212_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='doi',
            field=models.TextField(blank=True, help_text='a DOI will be added by Admin before publication.', null=True, verbose_name='DOI'),
        ),
    ]
