# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 22:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0028_auto_20200313_1433'),
        ('base', '0035_delete_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGeoLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.TextField(blank=True, db_column=b'wkt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupProfile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
            ],
        ),
        migrations.CreateModel(
            name='UserGeoLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.TextField(blank=True, db_column=b'wkt')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='groups_geolimits',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups_geolimits', to='base.GroupGeoLimit'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='users_geolimits',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_geolimits', to='base.UserGeoLimit'),
        ),
    ]
