# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-09 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20200402_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Configuration',
            },
        ),
    ]
