# Generated by Django 2.2.11 on 2020-03-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200305_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
