# Generated by Django 2.2.11 on 2020-03-18 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_merge_20200306_1153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0037_auto_20200305_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeoLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.TextField(blank=True, db_column='wkt')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupGeoLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.TextField(blank=True, db_column='wkt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.GroupProfile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
            ],
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='groups_geolimits',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups_geolimits', to='base.GroupGeoLimit'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='users_geolimits',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_geolimits', to='base.UserGeoLimit'),
        ),
    ]
