# Generated by Django 2.2.11 on 2020-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200305_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Configuration',
            },
        ),
    ]
