# Generated by Django 2.2.11 on 2020-05-15 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200305_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrapa_Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=255)),
                ('title', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Titles',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='autores',
            field=models.TextField(blank=True, help_text='Lista de autores separada por virgulas', max_length=3000, null=True, verbose_name='Lista de Autores'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='ano de criação do metadado', verbose_name='data criacao'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='is_inde',
            field=models.BooleanField(default=False, help_text='Publicar na INDE ?', verbose_name='INDE ?'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='link_vinde',
            field=models.CharField(blank=True, help_text='insira o link do visualizador da INDE - somente para CDGs publicados na INDE', max_length=255, null=True, verbose_name='Link VINDE'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='scale',
            field=models.CharField(blank=True, help_text='insira a escala utilizada', max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Permitido apenas números', regex='^[0-9]*$')], verbose_name='Escala '),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Is this resource validated from a publisher or editor?', verbose_name='Aprovado'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('fra', 'Frances'), ('ger', 'Deutsch'), ('ita', 'Italiano'), ('por', 'Portugues'), ('spa', 'Espanhol')], default='eng', help_text='language used within the dataset', max_length=3, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='metadata_uploaded_preserve',
            field=models.BooleanField(default=False, verbose_name='Preservação de update de metadados'),
        ),
        migrations.CreateModel(
            name='ResourceBase_Keywords_Embrapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embrapa_keywords', to='base.Embrapa_Keywords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='embrapa_keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='Lista de palavras-chave da Embrapa', through='base.ResourceBase_Keywords_Embrapa', to='base.Embrapa_Keywords', verbose_name='embrapa keywords'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='finalidade',
            field=models.ForeignKey(blank=True, help_text='summary of the intentions with which the resource(s) was developed', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Finalidade', verbose_name='Finalidade TESTE'),
        ),
    ]
