# Generated by Django 2.2.11 on 2020-05-18 19:15

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20200515_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords_Embrapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resourcebase_keywords_embrapa',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='resourcebase_keywords_embrapa',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='finalidade',
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='embrapa_keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='Lista de palavras-chave da Embrapa', through='base.Keywords_Embrapa', to='base.Embrapa_Keywords', verbose_name='embrapa keywords'),
        ),
        migrations.DeleteModel(
            name='Finalidade',
        ),
        migrations.DeleteModel(
            name='ResourceBase_Keywords_Embrapa',
        ),
        migrations.AddField(
            model_name='keywords_embrapa',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase'),
        ),
        migrations.AddField(
            model_name='keywords_embrapa',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embrapa_keywords', to='base.Embrapa_Keywords'),
        ),
    ]
