# Generated by Django 2.2.11 on 2020-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
