# Generated by Django 2.2.11 on 2020-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20200518_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='autores',
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='embrapa_autores',
            field=models.TextField(blank=True, help_text='Lista de autores separada por virgulas', max_length=3000, null=True, verbose_name='Lista de Autores'),
        ),
    ]
