# Generated by Django 2.2.11 on 2020-03-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_delete_backup'),
        ('base', '0039_auto_20200321_1338'),
    ]

    operations = [
    ]
