# Generated by Django 2.2.11 on 2020-05-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20200518_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbrapaUnity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity', models.IntegerField(default=96)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'ordering': ('unity',),
            },
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='embrapa_autores',
        ),
    ]
