# Generated by Django 2.2.11 on 2020-03-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20200318_0953'),
        ('base', '0040_merge_20200321_2245'),
    ]

    operations = [
    ]
