# Generated by Django 2.2.11 on 2020-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20200529_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrapaunity',
            name='unity',
            field=models.CharField(max_length=20),
        ),
    ]
