# Generated by Django 2.2.11 on 2020-03-23 19:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20200414_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='bbox_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, blank=True, srid=4326),
        ),
    ]
