# Generated by Django 2.2.11 on 2020-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20200529_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbrapaPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=300)),
                ('project_code', models.IntegerField(default=0)),
                ('title', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Finalidades',
                'ordering': ('title',),
            },
        ),
    ]
