# Generated by Django 2.2.12 on 2020-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20200414_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicalkeyword',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='hierarchicalkeyword',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
