# Generated by Django 2.2.11 on 2020-05-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_embrapapurpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=255)),
                ('embrapa_purpose', models.ForeignKey(blank=True, help_text='teste', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EmbrapaPurpose', verbose_name='EmbrapaPurpose')),
            ],
            options={
                'verbose_name_plural': 'Testes',
                'ordering': ('title',),
            },
        ),
    ]
