# Generated by Django 2.2.12 on 2020-05-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_resourcebase_bbox_polygon'),
        ('layers', '0028_auto_20200323_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_x0',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_x1',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_y0',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='bbox_y1',
        ),
    ]
