# Generated by Django 2.2.15 on 2020-10-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20201001_1514'),
        ('base', '0044_auto_20200901_1432'),
    ]

    operations = [
    ]
