# Generated by Django 2.2.11 on 2020-05-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='embrapa_purpose',
        ),
    ]
