# Generated by Django 2.2.15 on 2020-10-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20200507_0445'),
        ('base', '0045_merge_20201001_1617'),
    ]

    operations = [
    ]
