# Generated by Django 2.2.11 on 2020-05-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_teste_embrapa_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
