# Generated by Django 2.2.15 on 2020-10-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20200507_0445'),
        ('base', '0044_auto_20201001_1514'),
    ]

    operations = [
    ]
