# Generated by Django 2.2.15 on 2020-10-16 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_merge_20201016_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='bbox_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(default='POLYGON EMPTY', srid=4326),
        ),
    ]
