# Generated by Django 2.2.15 on 2020-10-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_merge_20201016_0709'),
        ('base', '0046_merge_20201016_0937'),
    ]

    operations = [
    ]
