# Generated by Django 2.2.11 on 2020-05-29 23:26

from django.db import migrations, models
import django.db.models.deletion
import geonode.security.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0046_delete_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=255)),
                ('embrapa_purpose', models.ForeignKey(blank=True, help_text='teste', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EmbrapaPurpose', verbose_name='EmbrapaPurpose')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_base.teste_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Testes',
                'ordering': ('title',),
            },
            bases=(geonode.security.models.PermissionLevelMixin, models.Model),
        ),
    ]
