# Generated by Django 2.2.11 on 2020-05-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
