# Generated by Django 2.2.16 on 2020-11-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_resourcebase_attribution'),
        ('base', '0047_resourcebase_attribution'),
    ]

    operations = [
    ]
