# Generated by Django 2.2.11 on 2020-05-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_delete_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='link_vinde',
        ),
    ]
