# Generated by Django 2.2.11 on 2020-05-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_resourcebase_link_vinde'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='link_vinde',
            field=models.CharField(blank=True, help_text='insira o link do visualizador da INDE - somente para CDGs publicados na INDE', max_length=255, null=True, verbose_name='Link VINDE'),
        ),
    ]
