# Generated by Django 2.2.16 on 2021-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20210201_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesaurus',
            name='card_max',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='thesaurus',
            name='card_min',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='thesaurus',
            name='facet',
            field=models.BooleanField(default=True),
        ),
    ]
