# Generated by Django 2.2.11 on 2020-05-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_resourcebase_link_vinde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Licenses',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='teste',
            field=models.ForeignKey(blank=True, help_text='license of the dataset', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Teste', verbose_name='License'),
        ),
    ]
