# Generated by Django 2.2.11 on 2020-05-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20200529_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmbrapaPurpose',
            new_name='PurposeEmbrapa',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='teste',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
