# Generated by Django 2.2.16 on 2021-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20210202_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesaurus',
            name='card_max',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='thesaurus',
            name='card_min',
            field=models.IntegerField(default=0),
        ),
    ]
