# Generated by Django 2.2.11 on 2020-05-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20200529_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrapa_Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=300)),
                ('project_code', models.IntegerField(default=0)),
                ('title', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Finalidades',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='embrapa_purpose',
            field=models.ForeignKey(blank=True, help_text='Escolha a finalidade do metadado', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Embrapa_Purpose', verbose_name='PurposeEmbrapa'),
        ),
    ]
