# Generated by Django 2.2.11 on 2020-05-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20200529_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='embrapa_purpose',
            field=models.ForeignKey(blank=True, help_text='Escolha a finalidade do metadado', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Embrapa_Purpose', verbose_name='EmbrapaPurpose'),
        ),
    ]
