# Generated by Django 2.2.11 on 2020-05-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20200529_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrapa_Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'ordering': ('unity',),
            },
        ),
    ]
