# Generated by Django 2.2.16 on 2021-03-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20210223_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesauruskeywordlabel',
            options={'ordering': ('keyword', 'lang'), 'verbose_name_plural': 'Thesaurus Keyword Labels'},
        ),
    ]
