# Generated by Django 2.2.16 on 2021-03-02 11:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20210302_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='ll_bbox_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
