# Generated by Django 2.2.11 on 2020-05-29 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_embrapa_unity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='embrapa_purpose',
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='purpose_embrapa',
            field=models.ForeignKey(blank=True, help_text='Escolha a finalidade do metadado', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PurposeEmbrapa', verbose_name='PurposeEmbrapa'),
        ),
    ]
