# Generated by Django 2.2.16 on 2021-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_resourcebase_ll_bbox_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='metadata_only',
            field=models.BooleanField(default=False, help_text='If true, will be excluded from search', verbose_name='Metadata'),
        ),
    ]
