# Generated by Django 2.2.16 on 2021-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_resourcebase_metadata_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesaurus',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
