# Generated by Django 2.2.16 on 2021-05-12 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_fill_empty_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_resource', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
