# Generated by Django 2.2.11 on 2020-05-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20200529_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='embrapa_purpose',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='unity_embrapa',
        ),
    ]
