# Generated by Django 2.2.11 on 2020-05-30 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20200529_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbrapaUnity',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='purpose_embrapa',
        ),
        migrations.DeleteModel(
            name='PurposeEmbrapa',
        ),
    ]
