# Generated by Django 3.2 on 2021-05-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20211117_1238'),
        ('base', '0060_resourcebase_state'),
    ]

    operations = [
    ]
