# Generated by Django 2.2.11 on 2020-05-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_auto_20200530_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Embrapa_Unity',
        ),
    ]
