# Generated by Django 3.2 on 2021-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_resourcebase_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='files',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
