# Generated by Django 2.2.24 on 2022-01-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_resourcebase_extra_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='extra_metadata',
        ),
        migrations.CreateModel(
            name='ExtraMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
            ],
        ),
    ]