# Generated by Django 2.2.24 on 2022-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20220128_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='metadata',
            field=models.ManyToManyField(blank=True, null=True, to='base.ExtraMetadata', verbose_name='Extra Metadata'),
        ),
    ]