# Generated by Django 3.2 on 2021-06-04 07:42

from django.db import migrations, models
from geonode.base.models import ResourceBase

def change_value(apps, schema_editor):
    resources = apps.get_model('base', 'ResourceBase')
    for r in resources.objects.all():
        if isinstance(r.files, dict):
            r2 = ResourceBase.objects.filter(id=r.id)
            f = list(r.files.values())
            r2.update(**{'files': f})

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_resourcebase_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(change_value, migrations.RunPython.noop),

    ]
