# Generated by Django 2.2.24 on 2022-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_resourcebase_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='metadata',
            field=models.ManyToManyField(blank=True, help_text='Additional metadata, must be in format [ {"metadata_key": "metadata_value"}, {"metadata_key": "metadata_value"} ]', null=True, to='base.ExtraMetadata', verbose_name='Extra Metadata'),
        ),
    ]
