# Generated by Django 3.2.4 on 2021-06-09 13:58

from django.db import migrations, models
import geonode.storage.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_resourcebase_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedthumbnail',
            name='img',
            field=models.ImageField(storage=geonode.storage.manager.StorageManager(), upload_to='curated_thumbs'),
        ),
    ]
