# Generated by Django 3.2 on 2021-06-04 07:42

from geonode.layers.utils import get_layer_storetype
from django.db import migrations
from geonode.layers.models import Layer

def change_value(apps, schema_editor):
    ll = Layer.objects.all()
    for l in ll:
        u = Layer.objects.filter(resourcebase_ptr_id=l.resourcebase_ptr_id)
        store_type = get_layer_storetype(l.storeType)
        u.update(**{"storeType": store_type})


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_resourcebase_files'),
    ]

    operations = [
        migrations.RunPython(change_value),

    ]
