# Generated by Django 2.2.11 on 2020-05-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20200530_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbrapaUnity',
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='purpose_embrapa',
        ),
        migrations.DeleteModel(
            name='PurposeEmbrapa',
        ),
    ]
