# Generated by Django 3.2 on 2021-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_curatedthumbnail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='blob',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
