# Generated by Django 2.2.11 on 2020-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_auto_20200530_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrapa_purpose',
            name='project_code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='embrapa_unity',
            name='unity',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
