# Generated by Django 3.2.4 on 2021-07-06 08:48

from geonode.base.models import ResourceBase
from django.db import migrations, models
from django.db.migrations.operations import RunPython


def clone_storetypes(apps, schema_editor):
    layers = apps.get_model('layers', 'Layer')
    documents = apps.get_model('documents', 'Document')
    for layer in layers.objects.all():
        ResourceBase.objects.filter(id=layer.resourcebase_ptr_id).update(storetype=layer.storeType)
    for doc in documents.objects.all():
        ResourceBase.objects.filter(id=doc.resourcebase_ptr_id).update(storetype=doc.storetype)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_resourcebase_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='storetype',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        RunPython(clone_storetypes)
    ]
