# Generated by Django 2.2.24 on 2022-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_auto_20220223_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesauruskeywordlabel',
            name='lang',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='thesauruslabel',
            name='lang',
            field=models.CharField(max_length=10),
        ),
    ]
