# Generated by Django 2.2.11 on 2020-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20200601_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrapa_unity',
            name='unity',
            field=models.CharField(default='96', max_length=20, unique=True),
        ),
    ]
