# Generated by Django 2.2.24 on 2022-04-03 13:34

from django.db import migrations, models
import geonode.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20220401_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='uuid',
            field=models.CharField(max_length=36, unique=True, default=geonode.base.models.ResourceBase.gen_uuid),
        ),
    ]
