# Generated by Django 3.2.4 on 2021-07-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_resourcebase_storetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcebase',
            old_name='storetype',
            new_name='subtype',
        ),
    ]
