# Generated by Django 3.2.4 on 2021-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_rename_storetype_resourcebase_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='sourcetype',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('REMOTE', 'REMOTE'), ('COPYREMOTE', 'COPYREMOTE')], default='LOCAL', help_text='The resource source type, which can be one of "LOCAL", "REMOTE" or "COPYREMOTE".', max_length=16, verbose_name='Source Type'),
        )
    ]
