# Generated by Django 2.2.11 on 2020-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_embrapa_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrapa_Last_Updated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('last_updated',),
            },
        ),
        migrations.DeleteModel(
            name='Embrapa_Last_Update',
        ),
    ]
