# Generated by Django 3.2.4 on 2021-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_resourcebase_sourcetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='ows_url',
            field=models.URLField(blank=True, default='http://localhost:8080/geoserver/ows', help_text='The URL of the OWS service providing this layer, if any exists.', null=True, verbose_name='ows URL'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='remote_typename',
            field=models.CharField(blank=True, help_text='Name of the Remote Service if any.', max_length=512, null=True, verbose_name='Remote Service Typename'),
        )
    ]
