# Generated by Django 3.2.4 on 2021-07-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20210720_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='ows_url',
        ),
    ]
