# Generated by Django 2.2.11 on 2020-06-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20200603_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embrapa_unity',
            name='unity',
            field=models.CharField(choices=[('1', 'um'), ('2', 'dois')], default='96', max_length=20, unique=True),
        ),
    ]
