# Generated by Django 3.2.4 on 2021-07-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_remove_resourcebase_ows_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='detail_url',
        ),
    ]
