# Generated by Django 2.2.11 on 2020-06-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_auto_20200603_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='embrapa_unity',
        ),
        migrations.DeleteModel(
            name='Embrapa_Unity',
        ),
    ]
