# Generated by Django 3.2.4 on 2021-09-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_remove_resourcebase_detail_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcebase',
            options={'permissions': (('change_resourcebase_permissions', 'Can change resource permissions'), ('download_resourcebase', 'Can download resource'), ('publish_resourcebase', 'Can publish resource'), ('approve_resourcebase', 'Can approve resource'), ('change_resourcebase_metadata', 'Can change resource metadata'))},
        ),
    ]
