# Generated by Django 2.2.11 on 2020-06-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_resourcebase_embrapa_unity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebase',
            name='embrapa_purpose',
        ),
        migrations.DeleteModel(
            name='Embrapa_Purpose',
        ),
    ]
