# Generated by Django 2.2.11 on 2020-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_auto_20200604_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='embrapa_data_quality_statement',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='embrapa data quality statement'),
        ),
    ]
