# Generated by Django 3.2.7 on 2022-01-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_drop_curated_thumbs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuratedThumbnail',
        ),
    ]
