# Generated by Django 2.2.11 on 2020-06-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_resourcebase_embrapa_data_quality_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrapa_Data_Quality_Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resourcebase',
            name='embrapa_data_quality_statement',
        ),
        migrations.CreateModel(
            name='Embrapa_Data_Quality_Statement_ResourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embrapa_data_quality_statement', to='base.Embrapa_Data_Quality_Statement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
