# Generated by Django 3.2.11 on 2022-02-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_resourcebase_metadata'),
        ('base', '0075_delete_curatedthumbnail'),
    ]

    operations = [
    ]
