# Generated by Django 3.2.12 on 2022-02-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20220128_0919'),
        ('base', '0076_merge_20220204_1339'),
    ]

    operations = [
    ]
