# Generated by Django 2.2.11 on 2020-06-08 11:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20200608_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='embrapa_data_quality_statement',
            field=taggit.managers.TaggableManager(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", through='base.Embrapa_Data_Quality_Statement_ResourceBase', to='base.Embrapa_Data_Quality_Statement', verbose_name='embrapa data quality statement'),
        ),
    ]
