# Generated by Django 2.2.11 on 2020-06-10 14:57

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_resourcebase_embrapa_data_quality_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embrapa_Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('afiliacao', models.CharField(max_length=50)),
                ('autoria', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Embrapa_Authors_ResourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ResourceBase')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embrapa_autores', to='base.Embrapa_Authors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='embrapa_autores',
            field=taggit.managers.TaggableManager(blank=True, help_text='lista de autores', through='base.Embrapa_Authors_ResourceBase', to='base.Embrapa_Authors', verbose_name='embrapa authors'),
        ),
    ]
