# Generated by Django 3.2.12 on 2022-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_alter_resourcebase_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='alternate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
