# Generated by Django 3.2.12 on 2022-04-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_alter_resourcebase_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='alternate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alternate'),
        ),
    ]
