# Generated by Django 3.2.12 on 2022-04-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_alter_resourcebase_alternate'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS dialogos_comment CASCADE;"),
    ]
