# Generated by Django 3.2.16 on 2022-11-08 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_remove_comments_from_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
