# Generated by Django 3.2.16 on 2023-03-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_resourcebase_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder_name', models.CharField(help_text='Name of the funding provider. (e.g. European Commission)', max_length=255)),
                ('funder_identifier', models.CharField(help_text='Uniquely identifies a funding entity, according to various types. (e.g. http://doi.org/10.13039/501100000780)', max_length=255)),
                ('funder_identifier_type', models.CharField(help_text='The type of the Identifier. (e.g. BMBF)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedIdentifierType',
            fields=[
                ('label', models.CharField(help_text='related identifier, available identifier types', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(help_text='label description', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('label', models.CharField(help_text='Description of the relationship of the resource being registered (A) and the related resource (B). If Related identifier is used Relation type is mandatory', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(help_text='label description', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='abstract_translated',
            field=models.TextField(blank=True, help_text='brief german narrative summary of the content of the resource(s)', max_length=2000, verbose_name='abstract_translated'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='method_description',
            field=models.TextField(blank=True, help_text='The methodology employed for the study or research', max_length=2000, verbose_name='method_description'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='other_description',
            field=models.TextField(blank=True, help_text='Other description information that does not fit into an existing category', max_length=2000, verbose_name='other_description'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='series_information',
            field=models.TextField(blank=True, help_text='Information about a repeating series, such as volumne, issue, number', max_length=2000, verbose_name='series_information'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='subtitle',
            field=models.TextField(blank=True, help_text='subtitle of the dataset', max_length=400, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='table_of_content',
            field=models.TextField(blank=True, help_text='A listing of the Table of Contents', max_length=2000, verbose_name='table_of_content'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='technical_info',
            field=models.TextField(blank=True, help_text='Detailed information that may be associated with design, implementation, operation, use, and/or maintenance of a process or system', max_length=2000, verbose_name='technical_info'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='title_translated',
            field=models.CharField(blank=True, help_text='german name by which the cited resource is known', max_length=255, verbose_name='title_translated'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='use_contraints',
            field=models.TextField(blank=True, help_text='This metadata element shall provide information on the Use constraints applied to assure the protection of privacy or intellectual property (e.g. Trademark)', max_length=2000, verbose_name='use_constraints'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='date_type',
            field=models.CharField(choices=[('publication', 'Publication')], default='publication', help_text='identification of when a given event occurred', max_length=255, verbose_name='date type'),
        ),
        migrations.CreateModel(
            name='RelatedIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_identifier', models.CharField(help_text='Identifiers of related resources. These must be globally unique identifiers.', max_length=255)),
                ('related_identifier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.relatedidentifiertype')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.relationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_number', models.CharField(help_text='The code assigned by the funder to a sponsored award (grant). (e.g. 282625)', max_length=255)),
                ('award_uri', models.CharField(help_text='The URI leading to a page provided by the funder for more information about the award (grant). (e.g. http://cordis.europa.eu/project/rcn/100180_en.html)', max_length=255)),
                ('award_title', models.CharField(help_text='The human readable title of the award (grant). (e.g. MOTivational strength of ecosystem services)', max_length=255)),
                ('funding_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.fundingreference')),
            ],
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='funders',
            field=models.ManyToManyField(blank=True, help_text='List of funders, funded dataset creators', null=True, to='base.Funder', verbose_name='Funder names'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='related_identifier',
            field=models.ManyToManyField(blank=True, help_text='Identifiers of related resources. These must be globally unique identifiers.', null=True, to='base.RelatedIdentifier', verbose_name='Related Identifier'),
        ),
    ]
