# Generated by Django 3.2.18 on 2023-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_auto_20230324_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='label of the hierarchy levels for which the metadata is provided. (e.g. SIGNAL)', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Name of the hierarchy levels for which the metadata is provided. (e.g. signal)', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='related_projects',
            field=models.ManyToManyField(blank=True, help_text='Name of the hierarchy levels for which the metadata is provided. (e.g. SIGNAL)', null=True, to='base.RelatedProject', verbose_name='related project'),
        ),
    ]
