# Generated by Django 3.2.18 on 2023-03-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_auto_20230329_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='use_constrains',
            field=models.ForeignKey(default=None, help_text='This metadata element shall provide information on the Use constraints applied to assure the protection of privacy or intellectual property (e.g. Trademark)', limit_choices_to=models.Q(('is_choice', True)), on_delete=django.db.models.deletion.CASCADE, related_name='use_constrains', to='base.restrictioncodetype', verbose_name='use_constrains'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='abstract',
            field=models.TextField(help_text='brief narrative summary of the content of the resource(s)', max_length=2000, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='abstract_translated',
            field=models.TextField(help_text='brief german narrative summary of the content of the resource(s)', max_length=2000, verbose_name='abstract_translated'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='restriction_code_type',
            field=models.ForeignKey(blank=True, help_text='limitation(s) placed upon the access or use of the data.', limit_choices_to=models.Q(('is_choice', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restriction_code_type', to='base.restrictioncodetype', verbose_name='restrictions'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='title_translated',
            field=models.CharField(help_text='german name by which the cited resource is known', max_length=255, verbose_name='title_translated'),
        ),
    ]
