# Generated by Django 3.2.22 on 2023-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_thesauruskeyword_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesauruskeyword',
            name='icon',
        ),
        migrations.AddField(
            model_name='thesauruskeyword',
            name='image',
            field=models.CharField(blank=True, help_text='A URL to an image', max_length=512, null=True),
        ),
    ]
