# Generated by Django 3.2.23 on 2024-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20231019_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='advertised',
            field=models.BooleanField(default=True, help_text='If False, will hide the resource from search results and catalog listings', verbose_name='Advertised'),
        ),
    ]
