# Generated by Django 4.2.9 on 2024-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0090_alter_resourcebase_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hierarchicalkeyword",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name="slug"),
        ),
    ]
