# Generated by Django 4.2.9 on 2024-04-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0091_alter_hierarchicalkeyword_slug"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="asset",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="assets.asset"),
        ),
        migrations.AlterField(
            model_name="link",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("original", "original"),
                    ("uploaded", "uploaded"),
                    ("data", "data"),
                    ("image", "image"),
                    ("metadata", "metadata"),
                    ("html", "html"),
                    ("OGC:WMS", "OGC:WMS"),
                    ("OGC:WFS", "OGC:WFS"),
                    ("OGC:WCS", "OGC:WCS"),
                ],
                max_length=255,
            ),
        ),
    ]
