# Generated by Django 3.2.18 on 2023-03-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_auto_20230330_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='conformity_explanation',
            field=models.CharField(blank=True, help_text='Give an Explanation about the conformity check. (e.g. See the referenced specification.', max_length=2000, null=True, verbose_name='conformity explanation'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='conformity_results',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Not Passed', 'Not Passed'), ('Unknown', 'Unknown')], default='Unknown', help_text='This is the degree of conformity of the dataset to the implementing rules the BonaRes Schema.', max_length=40, verbose_name='conformity result'),
        ),
        migrations.AlterField(
            model_name='resourcebase',
            name='date_type',
            field=models.CharField(choices=[('creation', 'Creation'), ('publication', 'Publication'), ('revision', 'Revision')], default='publication', help_text='identification of when a given event occurred', max_length=255, verbose_name='date type'),
        ),
    ]
