# Generated by Django 3.2.18 on 2023-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20230331_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='conformity_explanation',
            field=models.CharField(blank=True, default='', help_text='Give an Explanation about the conformity check. (e.g. See the referenced specification.', max_length=2000, verbose_name='conformity explanation'),
            preserve_default=False,
        ),
    ]
