# Generated by Django 4.2.20 on 2025-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0092_migrate and_remove_resourcebase_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesaurus",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
    ]