# Generated by Django 3.2.18 on 2023-03-31 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_resourcebase_parent_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='date_accepted',
            field=models.DateField(help_text='The date that the publisher accepted the resource into their system.', null=True, verbose_name='date accepted'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_available',
            field=models.DateField(default=datetime.date.today, help_text='The date the resource is made publicly available. To indicate the end of an embargo period.', verbose_name='date available'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_collected',
            field=models.DateField(help_text='The date or date range in which the dataset content was collected', null=True, verbose_name='date collected'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_copyrighted',
            field=models.DateField(help_text='The specific, documented date at which the dataset receives a copyrighted status, if applicable.', null=True, verbose_name='date copyrighted'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_created',
            field=models.DateField(default=datetime.date.today, help_text='The date the resource itself was put together; a single date for a final component, e.g. the finalised file with all of  the data.', verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_issued',
            field=models.DateField(help_text='The date that the resource is published or distributed e.g. to a data centre.', null=True, verbose_name='date issued'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_submitted',
            field=models.DateField(help_text='The date the creator submits the resource to the publisher. This could be different from Accepted if the publisher the applies a selection process. To indicate the start of an embargo period. ', null=True, verbose_name='date submitted'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_updated',
            field=models.DateField(default=datetime.date.today, help_text='The date of the last update (last revision) to the dataset, when the dataset is being added to.', verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='date_valid',
            field=models.DateField(help_text='The date or date range during which the dataset or resource is accurate.', null=True, verbose_name='date valid'),
        ),
    ]
