# Generated by Django 5.2 on 2025-10-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0095_alter_configuration_id_alter_contactrole_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="license",
            name="license_text_en",
        ),
        migrations.RemoveField(
            model_name="license",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="region",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="restrictioncodetype",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="restrictioncodetype",
            name="gn_description_en",
        ),
        migrations.RemoveField(
            model_name="spatialrepresentationtype",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="spatialrepresentationtype",
            name="gn_description_en",
        ),
        migrations.RemoveField(
            model_name="topiccategory",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="topiccategory",
            name="gn_description_en",
        ),
    ]
