# Generated by Django 3.2.22 on 2023-10-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20231019_1244'),
        ('base', '0095_auto_20230331_0923'),
    ]

    operations = [
    ]
