# Generated by Django 3.2.23 on 2024-06-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_merge_0088_auto_20231019_1244_0095_auto_20230331_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='metadata_license',
            field=models.ForeignKey(blank=True, help_text='license of the metadata', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_license', to='base.license', verbose_name='Metadata License'),
        ),
    ]
