# Generated by Django 5.2.10 on 2026-01-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("base", "0096_remove_modeltranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.asset",
            ),
        ),
    ]