# Generated by Django 5.2.12 on 2026-04-08 06:35

from django.db import migrations, models
from django.db.models import Q
import uuid

def populate_license_identifiers(apps, schema_editor):
    License = apps.get_model("base", "License")
    for lic in License.objects.filter(Q(identifier="") | Q(identifier__isnull=True)):
        lic.identifier = str(uuid.uuid4())
        lic.save(update_fields=["identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0097_alter_link_asset"),
    ]

    operations = [
        migrations.RunPython(populate_license_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="license",
            name="identifier",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
