# Generated by Django 5.2.12 on 2026-04-08 06:35

from django.db import migrations, models
from django.utils.text import slugify
import uuid
import logging

logger = logging.getLogger(__name__)

MAX_LEN = 255
SUFFIX_LEN = 7


def _base_identifier(lic):
    return slugify((lic.identifier or lic.abbreviation or "").strip()) or "license"


def _unique_identifier(base, seen):
    candidate = base[:MAX_LEN]
    if candidate not in seen:
        return candidate

    suffixed_base = base[: MAX_LEN - SUFFIX_LEN]
    candidate = f"{suffixed_base}-{uuid.uuid4().hex[:6]}"
    while candidate in seen:
        candidate = f"{suffixed_base}-{uuid.uuid4().hex[:6]}"
    return candidate


def populate_license_identifiers(apps, schema_editor):
    License = apps.get_model("base", "License")
    seen = set()

    for lic in License.objects.order_by("id"):
        current = (lic.identifier or "").strip()

        if current and current not in seen:
            seen.add(current)
            continue

        replacing_non_empty = bool(current)
        base = _base_identifier(lic)
        new_identifier = _unique_identifier(base, seen)

        if replacing_non_empty:
            logger.warning(
                "Replacing duplicate License.identifier '%s' (license id=%s) with '%s'",
                current,
                lic.id,
                new_identifier,
            )

        lic.identifier = new_identifier
        lic.save(update_fields=["identifier"])
        seen.add(new_identifier)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0097_alter_link_asset"),
    ]

    operations = [
        migrations.RunPython(populate_license_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="license",
            name="identifier",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
