# Generated by Django 5.2.13 on 2026-05-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0098_alter_license_identifier"),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcebase",
            name="auth_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authconfigresources",
                to="security.authconfig",
            ),
        ),
    ]
