# Generated by Django 3.2.23 on 2024-08-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20240822_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingreference',
            old_name='funder_identifier',
            new_name='ror',
        ),
        migrations.RemoveField(
            model_name='fundingreference',
            name='funder_identifier_type',
        ),
        migrations.RemoveField(
            model_name='fundingreference',
            name='funder_name',
        ),
        migrations.AddField(
            model_name='fundingreference',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='abbreviation of the Institutions names. (e.g. BMBF)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundingreference',
            name='address_information',
            field=models.CharField(blank=True, help_text='Address of the Institutions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundingreference',
            name='contact_information',
            field=models.CharField(blank=True, help_text='Contact Information of the Institutions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundingreference',
            name='name_of_the_institution',
            field=models.CharField(blank=True, help_text='Name of the institution provider. (e.g. European Commission)', max_length=255, null=True),
        ),
    ]
