# Generated by Django 5.2.17 on 2026-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0100_migrate_extrametadata_to_sparsefields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcebase",
            name="sourcetype",
            field=models.CharField(
                choices=[("LOCAL", "LOCAL"), ("REMOTE", "REMOTE")],
                default="LOCAL",
                help_text='The resource source type, which can be one of "LOCAL" or "REMOTE".',
                max_length=16,
                verbose_name="Source Type",
            ),
        ),
    ]
