# Generated by Django 5.2.17 on 2026-08-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0101_remove_source_type_copyremote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourcebase",
            options={
                "base_manager_name": "objects",
                "permissions": (
                    ("change_resourcebase_permissions", "Can change resource permissions"),
                    ("download_resourcebase", "Can download resource"),
                    ("publish_resourcebase", "Can publish resource"),
                    ("change_resourcebase_metadata", "Can change resource metadata"),
                ),
            },
        ),
    ]
