# Generated by Django 5.2 on 2025-10-23 16:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0096_remove_modeltranslation"),
    ]

    operations = [
        BtreeGinExtension(),
        
        migrations.CreateModel(
            name="ResourceIndex",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lang", models.CharField(max_length=16, null=True)),
                ("name", models.CharField(max_length=64)),
                ("vector", django.contrib.postgres.search.SearchVectorField()),
                ("resource", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.resourcebase")),
            ],
            options={
                "ordering": ("resource", "name", "lang"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(fields=["vector"], name="indexing_re_vector_164704_gin")
                ],
                "unique_together": {("resource", "lang", "name")},
            },
        ),
    ]
