# Generated by Django 3.2.4 on 2021-06-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_resource_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingworkflowtasks',
            options={'ordering': ('order',), 'verbose_name_plural': 'Processing Workflow Tasks'},
        ),
    ]
