# Generated by Django 5.2.17 on 2026-08-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_resource_processing", "0003_alter_abstractprocessingtask_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abstractprocessingtask",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sampleprocessingtask",
            options={},
        ),
    ]
