# Generated by Django 2.2.16 on 2020-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterproofNbsCa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
            ],
            options={
                'ordering': ['name', 'description'],
            },
        ),
    ]
