# Generated by Django 2.2.16 on 2020-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterproofnbsca',
            name='max_benefit_req_time',
            field=models.IntegerField(default=0, verbose_name='Time required to generate maximum benefit'),
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='periodicity_maitenance',
            field=models.IntegerField(default=0, verbose_name='Periodicity of maintenance (year)'),
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='profit_pct_time_inter_assoc',
            field=models.FloatField(default=0, verbose_name='Percentage of benefit associated with interventions at time t=0'),
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='total_profits_sbn_consec_time',
            field=models.IntegerField(default=0, verbose_name='Procurement time of total SBN benefits'),
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='unit_implementation_cost',
            field=models.FloatField(default=0, verbose_name='Unit implementation costs (US $/ha)'),
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='unit_maintenance_cost',
            field=models.FloatField(default=0, verbose_name='Unit maintenance costs (US $/ha)'),
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='unit_oportunity_cost',
            field=models.IntegerField(default=0, verbose_name='Unit oportunity costs (US $/ha)'),
        ),
    ]
