# Generated by Django 2.2.16 on 2020-11-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0003_auto_20201114_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterproofnbsca',
            name='rios_transition',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('archived', 'Archived - not available anymore')], default='1', max_length=32),
        ),
    ]
