# Generated by Django 2.2.16 on 2020-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0004_waterproofnbsca_rios_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterproofnbsca',
            name='land_cover_def',
            field=models.CharField(choices=[('nv', 'Forest'), ('rvU', 'Grassland'), ('rvA', 'Shrubland'), ('nv', 'Sparse vegetation')], default='1', max_length=32),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='rios_transition',
            field=models.CharField(choices=[('nv', 'Keep native vegetation'), ('rvU', 'Revegetation (unassisted)'), ('rvA', 'Revegetation (assisted)'), ('nv', 'Agricultural vegetation management'), ('di', 'Ditching'), ('rvA', 'Pasture management'), ('rvA', 'Fertilizer management')], default='1', max_length=32),
        ),
    ]
