# Generated by Django 2.2.16 on 2020-12-03 18:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_nbs_ca', '0006_auto_20201114_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiosTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('area', models.CharField(max_length=1024, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TramsformationShapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='waterproofnbsca',
            name='land_cover_def',
        ),
        migrations.RemoveField(
            model_name='waterproofnbsca',
            name='rios_transition',
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='total_profits_sbn_consec_time',
            field=models.FloatField(default=0, verbose_name='Procurement time of total SBN benefits'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_oportunity_cost',
            field=models.FloatField(default=0, verbose_name='Unit oportunity costs (US $/ha)'),
        ),
    ]
