# Generated by Django 2.2.16 on 2020-12-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0007_auto_20201203_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiosActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.RiosTransition')),
            ],
        ),
    ]
