# Generated by Django 2.2.16 on 2020-12-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0009_auto_20201203_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterproofnbsca',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.Countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.Currency'),
            preserve_default=False,
        ),
    ]
