# Generated by Django 2.2.16 on 2020-12-04 19:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0011_waterproofnbsca_rios_transformations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramsformationshapefile',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
