# Generated by Django 2.2.16 on 2020-12-04 19:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0012_auto_20201204_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramsformationshapefile',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326),
        ),
    ]
