# Generated by Django 2.2.16 on 2020-12-04 21:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0015_auto_20201204_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramsformationshapefile',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
