# Generated by Django 2.2.16 on 2020-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0017_remove_riostransition_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramsformationshapefile',
            old_name='polygon',
            new_name='area',
        ),
        migrations.AddField(
            model_name='riostransformation',
            name='unique_id',
            field=models.CharField(default=1, max_length=1024, verbose_name='Unique_id'),
            preserve_default=False,
        ),
    ]
