# Generated by Django 2.2.16 on 2020-12-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0017_remove_riostransition_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='periodicity_maitenance',
            field=models.TextField(default=0, verbose_name='Periodicity of maintenance (year)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='profit_pct_time_inter_assoc',
            field=models.TextField(default=0, verbose_name='Percentage of benefit associated with interventions at time t=0'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='total_profits_sbn_consec_time',
            field=models.TextField(default=0, verbose_name='Procurement time of total SBN benefits'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_implementation_cost',
            field=models.TextField(default=0, verbose_name='Unit implementation costs (US $/ha)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_maintenance_cost',
            field=models.TextField(default=0, verbose_name='Unit maintenance costs (US $/ha)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_oportunity_cost',
            field=models.TextField(default=0, verbose_name='Unit oportunity costs (US $/ha)'),
        ),
    ]
