# Generated by Django 2.2.16 on 2020-12-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0019_auto_20201212_0106'),
        ('waterproof_nbs_ca', '0018_auto_20201211_1808'),
    ]

    operations = [
    ]
