# Generated by Django 2.2.16 on 2020-12-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0020_merge_20201213_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='periodicity_maitenance',
            field=models.IntegerField(default=0, verbose_name='Periodicity of maintenance (year)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='profit_pct_time_inter_assoc',
            field=models.IntegerField(default=0, verbose_name='Percentage of benefit associated with interventions at time t=0'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='total_profits_sbn_consec_time',
            field=models.IntegerField(default=0, verbose_name='Procurement time of total SBN benefits'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_implementation_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unit implementation costs (US $/ha)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_maintenance_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unit maintenance costs (US $/ha)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_oportunity_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Unit oportunity costs (US $/ha)'),
        ),
    ]
