# Generated by Django 2.2.16 on 2020-12-17 23:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0024_auto_20201217_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityShapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='TramsformationShapefile',
        ),
        migrations.AddField(
            model_name='waterproofnbsca',
            name='activity_shapefile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.ActivityShapefile'),
            preserve_default=False,
        ),
    ]
