# Generated by Django 2.2.16 on 2020-12-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0026_countries_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
    ]
