# Generated by Django 2.2.16 on 2021-01-04 17:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_nbs_ca', '0027_remove_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='DemandParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_type', models.CharField(max_length=30, verbose_name='Interpolation type')),
                ('initial_extraction', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Initial extraction')),
                ('ending_extraction', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Ending extraction')),
                ('years_number', models.IntegerField(verbose_name='Years number')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Manual')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1980, verbose_name='Year')),
                ('water_volume', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Water_volume')),
                ('sediment', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('nitrogen', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('phosphorus', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEfficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('unitary_process', models.CharField(max_length=100, verbose_name='Unitary process')),
                ('symbol', models.CharField(max_length=100, verbose_name='Unitary process')),
                ('categorys', models.CharField(max_length=100, verbose_name='Categorys')),
                ('normalized_category', models.CharField(max_length=100, verbose_name='Normalized category')),
                ('minimal_sediment_perc', models.IntegerField(default=0, verbose_name='Minimal sediment')),
                ('predefined_sediment_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined sediment')),
                ('maximal_sediment_perc', models.IntegerField(default=0, verbose_name='Maximal sediment')),
                ('minimal_nitrogen_perc', models.IntegerField(default=0, verbose_name='Minimal nitrogen')),
                ('predefined_nitrogen_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined nitrogen')),
                ('maximal_nitrogen_perc', models.IntegerField(default=0, verbose_name='Maximal nitrogen')),
                ('minimal_phoshorus_perc', models.IntegerField(default=0, verbose_name='Minimal phosphorus')),
                ('predefined_phosphorus_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined phosphorus')),
                ('maximal_phosphorus_perc', models.IntegerField(default=0, verbose_name='Maximal phosphorus')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
            ],
        ),
        migrations.CreateModel(
            name='UserCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='WaterExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Year')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.DemandParameters')),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('water_source_name', models.CharField(max_length=100, verbose_name='Source name')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='geo')),
                ('xml_graph', models.TextField(verbose_name='Graph')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.City')),
                ('demand_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.DemandParameters')),
            ],
        ),
        migrations.CreateModel(
            name='ElementSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(default=1980, verbose_name='Year')),
                ('destination', models.IntegerField(default=1980, verbose_name='Year')),
                ('system_cost', models.ManyToManyField(to='waterproof_intake.SystemCosts')),
                ('user_cost', models.ManyToManyField(to='waterproof_intake.UserCosts')),
            ],
        ),
    ]
