# Generated by Django 2.2.16 on 2020-12-23 15:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0027_remove_currency_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='DemandParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_year', models.IntegerField(verbose_name='Year')),
                ('ending_year', models.IntegerField(verbose_name='Year')),
                ('interpolation_type', models.IntegerField(verbose_name='Year')),
                ('initial_extraction', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('ending_extraction', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Manual')),
            ],
        ),
        migrations.CreateModel(
            name='SystemCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
            ],
        ),
        migrations.CreateModel(
            name='UserCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Value')),
            ],
        ),
        migrations.RemoveField(
            model_name='intake',
            name='id_city',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='id_region',
        ),
        migrations.AddField(
            model_name='intake',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intake',
            name='area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='geo'),
        ),
        migrations.AddField(
            model_name='intake',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.Countries'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WaterExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1980, verbose_name='Year')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.DemandParameters')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1980, verbose_name='Year')),
                ('water_volume', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Water_volume')),
                ('sediment', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('nitrogen', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('phosphorus', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Extraction value')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake')),
            ],
        ),
        migrations.CreateModel(
            name='ElementSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(default=1980, verbose_name='Year')),
                ('destination', models.IntegerField(default=1980, verbose_name='Year')),
                ('system_cost', models.ManyToManyField(to='waterproof_intake.SystemCosts')),
                ('user_cost', models.ManyToManyField(to='waterproof_intake.UserCosts')),
            ],
        ),
        migrations.AddField(
            model_name='demandparameters',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.Countries')),
            ],
        ),
    ]
