# Generated by Django 2.2.16 on 2021-01-05 15:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processefficiencies',
            name='maximal_transp_water_perc',
            field=models.IntegerField(default=0, verbose_name='Maximal transported water'),
        ),
        migrations.AddField(
            model_name='processefficiencies',
            name='minimal_transp_water_perc',
            field=models.IntegerField(default=0, verbose_name='Minimal transported water'),
        ),
        migrations.AddField(
            model_name='processefficiencies',
            name='predefined_transp_water_perc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Predefined transported water'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intake',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='area'),
        ),
    ]
