# Generated by Django 2.2.16 on 2020-12-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0002_auto_20201223_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEfficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('unitary_process', models.CharField(max_length=100, verbose_name='Unitary process')),
                ('symbol', models.CharField(max_length=100, verbose_name='Unitary process')),
                ('categorys', models.CharField(max_length=100, verbose_name='Categorys')),
                ('minimal_sediment_perc', models.IntegerField(default=0, verbose_name='Minimal sediment')),
                ('predefined_sediment_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined sediment')),
                ('maximal_sediment_perc', models.IntegerField(default=0, verbose_name='Maximal sediment')),
                ('minimal_nitrogen_perc', models.IntegerField(default=0, verbose_name='Minimal nitrogen')),
                ('predefined_nitrogen_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined nitrogen')),
                ('maximal_nitrogen_perc', models.IntegerField(default=0, verbose_name='Maximal nitrogen')),
                ('minimal_phoshorus_perc', models.IntegerField(default=0, verbose_name='Minimal phosphorus')),
                ('predefined_phosphorus_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined phosphorus')),
                ('maximal_phosphorus_perc', models.IntegerField(default=0, verbose_name='Maximal phosphorus')),
            ],
        ),
        migrations.AlterField(
            model_name='intake',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.City'),
        ),
    ]
