# Generated by Django 2.2.16 on 2021-01-05 15:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0002_auto_20201223_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEfficiencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('unitary_process', models.CharField(max_length=100, verbose_name='Unitary process')),
                ('symbol', models.CharField(max_length=100, verbose_name='Unitary process')),
                ('categorys', models.CharField(max_length=100, verbose_name='Categorys')),
                ('normalized_category', models.CharField(max_length=100, verbose_name='Normalized category')),
                ('minimal_sediment_perc', models.IntegerField(default=0, verbose_name='Minimal sediment')),
                ('predefined_sediment_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined sediment')),
                ('maximal_sediment_perc', models.IntegerField(default=0, verbose_name='Maximal sediment')),
                ('minimal_nitrogen_perc', models.IntegerField(default=0, verbose_name='Minimal nitrogen')),
                ('predefined_nitrogen_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined nitrogen')),
                ('maximal_nitrogen_perc', models.IntegerField(default=0, verbose_name='Maximal nitrogen')),
                ('minimal_phoshorus_perc', models.IntegerField(default=0, verbose_name='Minimal phosphorus')),
                ('predefined_phosphorus_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined phosphorus')),
                ('maximal_phosphorus_perc', models.IntegerField(default=0, verbose_name='Maximal phosphorus')),
                ('minimal_transp_water_perc', models.IntegerField(default=0, verbose_name='Minimal transported water')),
                ('predefined_transp_water_perc', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Predefined transported water')),
                ('maximal_transp_water_perc', models.IntegerField(default=0, verbose_name='Maximal transported water')),
            ],
        ),
        migrations.RemoveField(
            model_name='demandparameters',
            name='ending_year',
        ),
        migrations.RemoveField(
            model_name='demandparameters',
            name='initial_year',
        ),
        migrations.RemoveField(
            model_name='demandparameters',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='externalinputs',
            name='intake',
        ),
        migrations.AddField(
            model_name='demandparameters',
            name='years_number',
            field=models.IntegerField(default=0, verbose_name='Years number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intake',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='demand_parameters',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.DemandParameters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intake',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='water_source_name',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Source name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intake',
            name='xml_graph',
            field=models.TextField(default='NULL', verbose_name='Graph'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandparameters',
            name='ending_extraction',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Ending extraction'),
        ),
        migrations.AlterField(
            model_name='demandparameters',
            name='initial_extraction',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Initial extraction'),
        ),
        migrations.AlterField(
            model_name='demandparameters',
            name='interpolation_type',
            field=models.CharField(max_length=30, verbose_name='Interpolation type'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.City'),
        ),
        migrations.AlterField(
            model_name='waterextraction',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Year'),
        ),
    ]
