# Generated by Django 2.2.16 on 2020-12-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0002_auto_20201223_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.City'),
        ),
    ]
