# Generated by Django 2.2.16 on 2021-01-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0003_auto_20210105_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementsystem',
            name='system_cost',
        ),
        migrations.RemoveField(
            model_name='elementsystem',
            name='user_cost',
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='nitrogen',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Extraction value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='normalized_category',
            field=models.CharField(default='', max_length=100, verbose_name='Normalized category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='phosphorus',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Extraction value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='sediment',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Extraction value'),
            preserve_default=False,
        ),
    ]
