# Generated by Django 2.2.16 on 2021-01-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0004_auto_20210107_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsystem',
            name='intake',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalinputs',
            name='intake',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake'),
            preserve_default=False,
        ),
    ]
