# Generated by Django 2.2.16 on 2021-01-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0005_auto_20210107_0037'),
        ('waterproof_intake', '0002_auto_20210105_1500'),
    ]

    operations = [
    ]
