# Generated by Django 2.2.16 on 2021-01-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0006_merge_20210107_2140'),
        ('waterproof_intake', '0006_merge_20210107_2134'),
    ]

    operations = [
    ]
