# Generated by Django 2.2.16 on 2021-01-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0007_merge_20210107_2316'),
        ('waterproof_intake', '0006_merge_20210108_1532'),
    ]

    operations = [
    ]
