# Generated by Django 2.2.16 on 2021-01-08 20:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0007_merge_20210107_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='geom')),
                ('continent', models.CharField(max_length=254, verbose_name='Continent')),
                ('symbol', models.CharField(max_length=254, verbose_name='Symbol')),
                ('code', models.IntegerField(default=0, verbose_name='Code')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('x_min', models.FloatField(default=None, verbose_name='Xmin')),
                ('x_max', models.FloatField(default=None, verbose_name='Xmax')),
                ('y_min', models.FloatField(default=None, verbose_name='Ymin')),
                ('y_max', models.FloatField(default=None, verbose_name='Ymax')),
            ],
        ),
        migrations.CreateModel(
            name='CostFunctionsProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, verbose_name='Symbol')),
                ('categorys', models.CharField(max_length=100, verbose_name='Categorys')),
                ('normalized_category', models.CharField(max_length=100, verbose_name='Normalized category')),
                ('energy', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Energy')),
                ('labour', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Labour')),
                ('mater_equipment', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Materials equipment')),
                ('function', models.CharField(max_length=1000, verbose_name='Function')),
                ('function_name', models.CharField(max_length=250, verbose_name='Function name')),
                ('function_description', models.CharField(max_length=250, verbose_name='Function description')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='geom')),
                ('delimitation_date', models.DateField(auto_now=True)),
                ('delimitation_type', models.CharField(max_length=30, verbose_name='Delimitation type')),
                ('basin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Basins')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryCosts',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='area',
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='awy',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Awy'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='cn_mg_l',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Cn'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='cp_mg_l',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CpMgl'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='csed_mg_l',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CsedMgL'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='q_l_s',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Qls'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='wn_kg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='wn_ret_kg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='WnRetKg'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='wp_ret_ton',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetTon'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='wsed_ret_ton',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='WsedRetTon'),
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='wsed_ton',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon'),
        ),
        migrations.AlterField(
            model_name='processefficiencies',
            name='symbol',
            field=models.CharField(max_length=100, verbose_name='Symbol'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake'),
        ),
    ]
