# Generated by Django 2.2.16 on 2021-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0009_remove_costfunctionsprocess_normalized_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfunctionsprocess',
            name='function_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Function description'),
        ),
    ]
