# Generated by Django 2.2.16 on 2021-01-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0010_auto_20210108_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costfunctionsprocess',
            old_name='function',
            new_name='function_value',
        ),
    ]
