# Generated by Django 2.2.16 on 2021-01-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0008_merge_20210108_1558'),
        ('waterproof_intake', '0011_auto_20210108_2056'),
    ]

    operations = [
    ]
