# Generated by Django 2.2.16 on 2021-01-12 20:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0013_auto_20210112_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='geom'),
        ),
    ]
