# Generated by Django 2.2.16 on 2021-01-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0015_auto_20210112_2005'),
        ('waterproof_intake', '0008_merge_20210108_1558'),
    ]

    operations = [
    ]
