# Generated by Django 2.2.16 on 2021-01-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0012_merge_20210112_1435'),
        ('waterproof_intake', '0016_merge_20210113_0215'),
    ]

    operations = [
    ]
