# Generated by Django 2.2.16 on 2021-01-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0017_merge_20210113_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementsystem',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='elementsystem',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='externalinputs',
            name='intake',
        ),
        migrations.AddField(
            model_name='elementsystem',
            name='wp_kg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg'),
        ),
        migrations.AddField(
            model_name='externalinputs',
            name='element',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.ElementSystem'),
            preserve_default=False,
        ),
    ]
