# Generated by Django 2.2.16 on 2021-01-14 03:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0018_auto_20210114_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='geomIntake',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='geom'),
        ),
    ]
