# Generated by Django 2.2.16 on 2021-01-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0006_merge_20210108_0044'),
        ('waterproof_intake', '0020_auto_20210114_0347'),
    ]

    operations = [
    ]
