# Generated by Django 2.2.16 on 2021-01-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0021_elementconnections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementconnections',
            name='element',
        ),
        migrations.AddField(
            model_name='elementconnections',
            name='source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='waterproof_intake.ElementSystem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementconnections',
            name='target',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='waterproof_intake.ElementSystem'),
            preserve_default=False,
        ),
    ]
