# Generated by Django 2.2.16 on 2021-01-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0022_auto_20210115_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsystem',
            name='graphId',
            field=models.IntegerField(default=0),
        ),
    ]
