# Generated by Django 2.2.16 on 2021-01-18 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_intake', '0023_elementsystem_graphid'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsystem',
            name='transported_water',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Extraction value'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='userCostFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=250, null=True, verbose_name='Function')),
                ('template_function', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='waterproof_intake.CostFunctionsProcess')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
