# Generated by Django 2.2.16 on 2021-01-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0024_auto_20210118_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalInputs',
            new_name='ValuesTime',
        ),
    ]
