# Generated by Django 2.2.16 on 2021-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0025_auto_20210118_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsystem',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='External'),
        ),
    ]
