# Generated by Django 2.2.16 on 2021-01-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0027_elementsystem_id_wb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementsystem',
            name='id_wb',
        ),
        migrations.AddField(
            model_name='processefficiencies',
            name='id_wb',
            field=models.IntegerField(default=0, verbose_name='ID Wb'),
        ),
    ]
