# Generated by Django 2.2.16 on 2021-01-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0021_merge_20210115_0145'),
        ('waterproof_intake', '0028_auto_20210119_1314'),
    ]

    operations = [
    ]
