# Generated by Django 2.2.16 on 2021-01-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0029_merge_20210119_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsystem',
            name='nitrogen',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Extraction value'),
        ),
        migrations.AlterField(
            model_name='elementsystem',
            name='phosphorus',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Extraction value'),
        ),
        migrations.AlterField(
            model_name='elementsystem',
            name='sediment',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Extraction value'),
        ),
        migrations.AlterField(
            model_name='elementsystem',
            name='transported_water',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Extraction value'),
        ),
        migrations.AlterField(
            model_name='processefficiencies',
            name='predefined_nitrogen_perc',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Predefined nitrogen'),
        ),
        migrations.AlterField(
            model_name='processefficiencies',
            name='predefined_phosphorus_perc',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Predefined phosphorus'),
        ),
        migrations.AlterField(
            model_name='processefficiencies',
            name='predefined_sediment_perc',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Predefined sediment'),
        ),
        migrations.AlterField(
            model_name='processefficiencies',
            name='predefined_transp_water_perc',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Predefined transported water'),
        ),
        migrations.AlterField(
            model_name='valuestime',
            name='nitrogen',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Extraction value'),
        ),
        migrations.AlterField(
            model_name='valuestime',
            name='phosphorus',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Extraction value'),
        ),
        migrations.AlterField(
            model_name='valuestime',
            name='sediment',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Extraction value'),
        ),
        migrations.AlterField(
            model_name='valuestime',
            name='water_volume',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Water_volume'),
        ),
    ]
