# Generated by Django 2.2.16 on 2021-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0030_auto_20210119_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='geomIntake',
            field=models.CharField(default='', max_length=2500, verbose_name='Geom intake'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polygon',
            name='geomPoint',
            field=models.CharField(default='', max_length=2500, verbose_name='Geom point'),
            preserve_default=False,
        ),
    ]
