# Generated by Django 2.2.16 on 2021-01-28 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0031_auto_20210125_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='area',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='geomIntake',
            field=models.TextField(verbose_name='Geom intake'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='geomPoint',
            field=models.TextField(verbose_name='Geom point'),
        ),
        migrations.AlterField(
            model_name='usercostfunctions',
            name='function',
            field=models.TextField(default='', verbose_name='Function'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercostfunctions',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
