# Generated by Django 2.2.16 on 2021-01-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0032_auto_20210128_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
