name: Sahred Docker image action

inputs:
  image:
    required: true
  tag:
    required: true
  branch:
    default: "master"
  push:
    default: false
  username:
    required: true
  password:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ./docker/${{ inputs.image }}/Dockerfile
        context: "./docker/${{ inputs.image }}/"
        push: ${{ inputs.push }}
        tags: geonode/${{ inputs.image }}:${{ inputs.tag }}
