# Generated by Django 1.9.13 on 2018-03-02 10:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0026_auto_20180301_1947'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='map',
            managers=[
            ],
        ),
    ]
