# Generated by Django 1.11.25 on 2019-10-28 14:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_auto_20190516_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='store',
            field=models.TextField(null=True, verbose_name='store'),
        ),
    ]
