# Generated by Django 2.2.15 on 2020-10-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_maplayer_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapSnapshot',
        ),
    ]
