# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-20 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_auto_20180319_0806'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='map',
            managers=[
            ],
        ),
    ]
