# Generated by Django 3.2 on 2021-06-15 07:17

from django.db import migrations

move_data_blob = '''
UPDATE base_resourcebase
SET "blob"=subquery."blob"
FROM (select resource_id,"blob" from maps_mapdata gg) AS subquery
WHERE base_resourcebase.id=subquery.resource_id;
'''

class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0030_auto_20210506_0836'),
        ('base', '0066_resourcebase_data'),
    ]

    operations = [
        migrations.RunSQL(move_data_blob),
        migrations.RemoveField(
            model_name='map',
            name='data',
        ),
        migrations.DeleteModel(
            name='MapData',
        ),
    ]
