# Generated by Django 3.2.4 on 2021-07-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0031_auto_20210615_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='ows_url',
        ),
    ]
