# Generated by Django 3.2 on 2021-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0031_remove_map_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapData',
        ),
    ]
