# Generated by Django 3.2.4 on 2021-07-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0031_auto_20210615_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplayer',
            old_name='layer_params',
            new_name='dataset_params',
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_set', to='maps.map'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='dataset_params',
            field=models.TextField(verbose_name='dataset params'),
        ),
    ]
