# Generated by Django 2.2.20 on 2021-05-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0030_auto_20210506_0836'),
        ('maps', '0033_map_blob_migration'),
    ]

    operations = [
    ]
