# Generated by Django 3.2.7 on 2021-11-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0034_maplayer_extra_params_and_current_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maplayers', to='maps.map'),
        ),
    ]
