# Generated by Django 3.2.7 on 2021-11-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0037_datamigration_maplayer_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maplayers', to='maps.map'),
        ),
    ]
