# Generated by Django 3.2.7 on 2021-11-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0038_alter_maplayer_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='dataset_params',
            field=models.TextField(blank=True, default='{}', verbose_name='dataset params'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='fixed',
            field=models.BooleanField(blank=True, default=False, verbose_name='fixed'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='local',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='opacity',
            field=models.FloatField(blank=True, default=1.0, verbose_name='opacity'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='source_params',
            field=models.TextField(blank=True, default='{}', verbose_name='source params'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='stack_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='stack order'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='store',
            field=models.TextField(blank=True, null=True, verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='transparent',
            field=models.BooleanField(blank=True, default=False, verbose_name='transparent'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='visibility',
            field=models.BooleanField(blank=True, default=True, verbose_name='visibility'),
        ),
    ]
