# Generated by Django 3.2.7 on 2021-11-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0039_set_legacy_fields_as_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='dataset_params',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='format',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='source_params',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='stack_order',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='transparent',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='visibility',
        ),
    ]
