# Generated by Django 3.2.7 on 2021-11-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0040_remove_maplayer_legacy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='center_x',
        ),
        migrations.RemoveField(
            model_name='map',
            name='center_y',
        ),
        migrations.RemoveField(
            model_name='map',
            name='projection',
        ),
        migrations.RemoveField(
            model_name='map',
            name='zoom',
        ),
    ]
