# Generated by Django 3.2.7 on 2021-11-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0041_remove_map_legacy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='styles',
        ),
    ]
