# Generated by Django 3.2.19 on 2023-08-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0042_remove_maplayer_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='opacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
