# Generated by Django 5.2 on 2025-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0043_auto_20230807_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maplayer",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
