# Generated by Django 3.2.20 on 2023-08-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0043_alter_map_abstract_en'),
        ('maps', '0043_auto_20230807_1234'),
    ]

    operations = [
    ]
