# Generated by Django 3.2.23 on 2024-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0045_alter_map_constraints_other_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='abstract_en',
            field=models.CharField(help_text='brief narrative summary of the content of the resource(s)', max_length=2000, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='map',
            name='constraints_other_en',
            field=models.TextField(blank=True, help_text='other restrictions and legal prerequisites for accessing and using the resource or metadata by User', null=True, verbose_name='Other Constraints'),
        ),
        migrations.AlterField(
            model_name='map',
            name='data_quality_statement_en',
            field=models.TextField(blank=True, help_text="general explanation of the data producer's knowledge about the lineage of a dataset", max_length=2000, null=True, verbose_name='Data Quality Statement'),
        ),
        migrations.AlterField(
            model_name='map',
            name='purpose_en',
            field=models.TextField(blank=True, help_text='summary of the intentions with which the resource(s) was developed', max_length=500, null=True, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='map',
            name='supplemental_information_en',
            field=models.TextField(default='No information provided', help_text='any other descriptive information about the dataset', max_length=2000, null=True, verbose_name='Supplemental Information'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title_en',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
