# Generated by Django 5.2.17 on 2026-08-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0045_remove_modeltranslation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="map",
            options={},
        ),
    ]
