# Generated by Django 2.1.4 on 2018-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequently', '0002_auto_20150911_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='validation',
            field=models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], max_length=1, verbose_name='Validation mood'),
        ),
    ]
