# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
