# Generated by Django 4.2.9 on 2024-08-30 09:22

import json
from django.db import migrations, models
from geonode.metadata.models import UISchemaModel
from geonode.metadata import metadata_path

def forwards_func(apps, schema_editor):
    # creating default ui schema
    with open(f"{metadata_path}/fixtures/ui_schema.json", "r") as f:
        ui_schema = json.load(f)
    UISchemaModel.objects.create(
        title="Geonode UI Schema",
        ui_schema_json = ui_schema,
        active = True
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UISchemaModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("ui_schema_json", models.JSONField()),
                ("active", models.BooleanField()),
            ],
            options={
                "verbose_name": "Ui Schema",
                "verbose_name_plural": "Ui Schema Management",
            },
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
