# Generated by Django 1.9.13 on 2018-03-02 10:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_auto_20180301_1947'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
            ],
        ),
    ]
