# Generated by Django 2.2.10 on 2020-03-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_auto_20190429_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentresourcelink',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='documentresourcelink',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='documents.Document'),
        ),
    ]
