# Generated by Django 2.2.16 on 2020-11-07 22:41

from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_auto_20200305_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='File'),
        ),
    ]
