# Generated by Django 3.2 on 2021-05-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20201107_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_file',
        ),
    ]
