# Generated by Django 3.2.4 on 2021-07-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_remove_document_doc_file'),
        ('base', '0067_resourcebase_storetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
    ]
