# Generated by Django 3.2.22 on 2023-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_delete_documentresourcelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_url',
            field=models.URLField(blank=True, help_text='The URL of the document if it is external.', max_length=512, null=True, verbose_name='URL'),
        ),
    ]
