# Generated by Django 5.2 on 2025-10-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0038_alter_document_doc_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="abstract_en",
        ),
        migrations.RemoveField(
            model_name="document",
            name="constraints_other_en",
        ),
        migrations.RemoveField(
            model_name="document",
            name="data_quality_statement_en",
        ),
        migrations.RemoveField(
            model_name="document",
            name="purpose_en",
        ),
        migrations.RemoveField(
            model_name="document",
            name="supplemental_information_en",
        ),
        migrations.RemoveField(
            model_name="document",
            name="title_en",
        ),
    ]
