# Generated by Django 2.2.11 on 2020-03-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgis_server', '0005_auto_20170823_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgisserverlayer',
            name='base_layer_path',
            field=models.CharField(help_text='Location of the base layer.', max_length=2000, verbose_name='Base Layer Path'),
        ),
    ]
