name: "Code formatting"

on:
  push:
    branches: [ master, 5.* ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master, 5.* ]

jobs:
  validate:

    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.12']

    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]'}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Install ruff
      run: pip install $(grep "ruff==" pyproject.toml | sed -E 's/^[^"]*"//; s/".*$//; s/,//')

    - name: "Check: ruff"
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff check
